/// Maps sender location / country names to postcard illustration CDN URLs.
///
/// Generated from country.csv + jpg-by-country-id filenames hosted at
/// https://www.fairytrail.app/img-assets/postcards/. Unknown locations fall
/// back to [defaultAsset].
abstract final class PostcardArt {
  static const defaultAsset = 'assets/trailBook/countries/default.png';

  static const _urls = <String, String>{
    'abw': 'https://www.fairytrail.app/img-assets/postcards/12%20-%20Aruba.jpg',
    'ad': 'https://www.fairytrail.app/img-assets/postcards/5%20-%20Andorra.jpg',
    'ae': 'https://www.fairytrail.app/img-assets/postcards/227%20-%20United%20Arab%20Emirates.jpg',
    'af': 'https://www.fairytrail.app/img-assets/postcards/1%20-%20Afghanistan.jpg',
    'afg': 'https://www.fairytrail.app/img-assets/postcards/1%20-%20Afghanistan.jpg',
    'afghanistan': 'https://www.fairytrail.app/img-assets/postcards/1%20-%20Afghanistan.jpg',
    'ag': 'https://www.fairytrail.app/img-assets/postcards/9%20-%20Antigua%20and%20Barbuda.jpg',
    'ago': 'https://www.fairytrail.app/img-assets/postcards/6%20-%20Angola.jpg',
    'ai': 'https://www.fairytrail.app/img-assets/postcards/7%20-%20Anguilla.jpg',
    'aia': 'https://www.fairytrail.app/img-assets/postcards/7%20-%20Anguilla.jpg',
    'al': 'https://www.fairytrail.app/img-assets/postcards/2%20-%20Albania.jpg',
    'alb': 'https://www.fairytrail.app/img-assets/postcards/2%20-%20Albania.jpg',
    'albania': 'https://www.fairytrail.app/img-assets/postcards/2%20-%20Albania.jpg',
    'algeria': 'https://www.fairytrail.app/img-assets/postcards/3%20-%20Algeria.jpg',
    'am': 'https://www.fairytrail.app/img-assets/postcards/11%20-%20Armenia.jpg',
    'america': 'https://www.fairytrail.app/img-assets/postcards/229%20-%20United%20States.jpg',
    'american samoa': 'https://www.fairytrail.app/img-assets/postcards/4%20-%20American%20Samoa.jpg',
    'an': 'https://www.fairytrail.app/img-assets/postcards/149%20-%20Netherlands%20Antilles.jpg',
    'and': 'https://www.fairytrail.app/img-assets/postcards/5%20-%20Andorra.jpg',
    'andorra': 'https://www.fairytrail.app/img-assets/postcards/5%20-%20Andorra.jpg',
    'angola': 'https://www.fairytrail.app/img-assets/postcards/6%20-%20Angola.jpg',
    'anguilla': 'https://www.fairytrail.app/img-assets/postcards/7%20-%20Anguilla.jpg',
    'ant': 'https://www.fairytrail.app/img-assets/postcards/149%20-%20Netherlands%20Antilles.jpg',
    'antarctica': 'https://www.fairytrail.app/img-assets/postcards/8%20-%20Antarctica.jpg',
    'antigua and barbuda': 'https://www.fairytrail.app/img-assets/postcards/9%20-%20Antigua%20and%20Barbuda.jpg',
    'ao': 'https://www.fairytrail.app/img-assets/postcards/6%20-%20Angola.jpg',
    'aq': 'https://www.fairytrail.app/img-assets/postcards/8%20-%20Antarctica.jpg',
    'ar': 'https://www.fairytrail.app/img-assets/postcards/10%20-%20Argentina.jpg',
    'are': 'https://www.fairytrail.app/img-assets/postcards/227%20-%20United%20Arab%20Emirates.jpg',
    'arg': 'https://www.fairytrail.app/img-assets/postcards/10%20-%20Argentina.jpg',
    'argentina': 'https://www.fairytrail.app/img-assets/postcards/10%20-%20Argentina.jpg',
    'arm': 'https://www.fairytrail.app/img-assets/postcards/11%20-%20Armenia.jpg',
    'armenia': 'https://www.fairytrail.app/img-assets/postcards/11%20-%20Armenia.jpg',
    'aruba': 'https://www.fairytrail.app/img-assets/postcards/12%20-%20Aruba.jpg',
    'as': 'https://www.fairytrail.app/img-assets/postcards/4%20-%20American%20Samoa.jpg',
    'asm': 'https://www.fairytrail.app/img-assets/postcards/4%20-%20American%20Samoa.jpg',
    'at': 'https://www.fairytrail.app/img-assets/postcards/14%20-%20Austria.jpg',
    'ata': 'https://www.fairytrail.app/img-assets/postcards/8%20-%20Antarctica.jpg',
    'atg': 'https://www.fairytrail.app/img-assets/postcards/9%20-%20Antigua%20and%20Barbuda.jpg',
    'au': 'https://www.fairytrail.app/img-assets/postcards/13%20-%20Australia.jpg',
    'aus': 'https://www.fairytrail.app/img-assets/postcards/13%20-%20Australia.jpg',
    'australia': 'https://www.fairytrail.app/img-assets/postcards/13%20-%20Australia.jpg',
    'austria': 'https://www.fairytrail.app/img-assets/postcards/14%20-%20Austria.jpg',
    'aut': 'https://www.fairytrail.app/img-assets/postcards/14%20-%20Austria.jpg',
    'aw': 'https://www.fairytrail.app/img-assets/postcards/12%20-%20Aruba.jpg',
    'az': 'https://www.fairytrail.app/img-assets/postcards/15%20-%20Azerbaijan.jpg',
    'aze': 'https://www.fairytrail.app/img-assets/postcards/15%20-%20Azerbaijan.jpg',
    'azerbaijan': 'https://www.fairytrail.app/img-assets/postcards/15%20-%20Azerbaijan.jpg',
    'ba': 'https://www.fairytrail.app/img-assets/postcards/27%20-%20Bosnia%20and%20Herzegovina.jpg',
    'bahamas': 'https://www.fairytrail.app/img-assets/postcards/16%20-%20Bahamas.jpg',
    'bahrain': 'https://www.fairytrail.app/img-assets/postcards/17%20-%20Bahrain.jpg',
    'bangladesh': 'https://www.fairytrail.app/img-assets/postcards/18%20-%20Bangladesh.jpg',
    'barbados': 'https://www.fairytrail.app/img-assets/postcards/19%20-%20Barbados.jpg',
    'bb': 'https://www.fairytrail.app/img-assets/postcards/19%20-%20Barbados.jpg',
    'bd': 'https://www.fairytrail.app/img-assets/postcards/18%20-%20Bangladesh.jpg',
    'bdi': 'https://www.fairytrail.app/img-assets/postcards/35%20-%20Burundi.jpg',
    'be': 'https://www.fairytrail.app/img-assets/postcards/21%20-%20Belgium.jpg',
    'bel': 'https://www.fairytrail.app/img-assets/postcards/21%20-%20Belgium.jpg',
    'belarus': 'https://www.fairytrail.app/img-assets/postcards/20%20-%20Belarus.jpg',
    'belgium': 'https://www.fairytrail.app/img-assets/postcards/21%20-%20Belgium.jpg',
    'belize': 'https://www.fairytrail.app/img-assets/postcards/22%20-%20Belize.jpg',
    'ben': 'https://www.fairytrail.app/img-assets/postcards/23%20-%20Benin.jpg',
    'benin': 'https://www.fairytrail.app/img-assets/postcards/23%20-%20Benin.jpg',
    'bermuda': 'https://www.fairytrail.app/img-assets/postcards/24%20-%20Bermuda.jpg',
    'bf': 'https://www.fairytrail.app/img-assets/postcards/34%20-%20Burkina%20Faso.jpg',
    'bfa': 'https://www.fairytrail.app/img-assets/postcards/34%20-%20Burkina%20Faso.jpg',
    'bg': 'https://www.fairytrail.app/img-assets/postcards/33%20-%20Bulgaria.jpg',
    'bgd': 'https://www.fairytrail.app/img-assets/postcards/18%20-%20Bangladesh.jpg',
    'bgr': 'https://www.fairytrail.app/img-assets/postcards/33%20-%20Bulgaria.jpg',
    'bh': 'https://www.fairytrail.app/img-assets/postcards/17%20-%20Bahrain.jpg',
    'bhr': 'https://www.fairytrail.app/img-assets/postcards/17%20-%20Bahrain.jpg',
    'bhs': 'https://www.fairytrail.app/img-assets/postcards/16%20-%20Bahamas.jpg',
    'bhutan': 'https://www.fairytrail.app/img-assets/postcards/25%20-%20Bhutan.jpg',
    'bi': 'https://www.fairytrail.app/img-assets/postcards/35%20-%20Burundi.jpg',
    'bih': 'https://www.fairytrail.app/img-assets/postcards/27%20-%20Bosnia%20and%20Herzegovina.jpg',
    'bj': 'https://www.fairytrail.app/img-assets/postcards/23%20-%20Benin.jpg',
    'bl': 'https://www.fairytrail.app/img-assets/postcards/178%20-%20Saint%20Barthelemy.jpg',
    'blm': 'https://www.fairytrail.app/img-assets/postcards/178%20-%20Saint%20Barthelemy.jpg',
    'blr': 'https://www.fairytrail.app/img-assets/postcards/20%20-%20Belarus.jpg',
    'blz': 'https://www.fairytrail.app/img-assets/postcards/22%20-%20Belize.jpg',
    'bm': 'https://www.fairytrail.app/img-assets/postcards/24%20-%20Bermuda.jpg',
    'bmu': 'https://www.fairytrail.app/img-assets/postcards/24%20-%20Bermuda.jpg',
    'bn': 'https://www.fairytrail.app/img-assets/postcards/32%20-%20Brunei.jpg',
    'bo': 'https://www.fairytrail.app/img-assets/postcards/26%20-%20Bolivia.jpg',
    'bol': 'https://www.fairytrail.app/img-assets/postcards/26%20-%20Bolivia.jpg',
    'bolivia': 'https://www.fairytrail.app/img-assets/postcards/26%20-%20Bolivia.jpg',
    'bonaire': 'https://www.fairytrail.app/img-assets/postcards/242%20-%20Bonaire.jpg',
    'bosnia and herzegovina': 'https://www.fairytrail.app/img-assets/postcards/27%20-%20Bosnia%20and%20Herzegovina.jpg',
    'botswana': 'https://www.fairytrail.app/img-assets/postcards/28%20-%20Botswana.jpg',
    'bq': 'https://www.fairytrail.app/img-assets/postcards/242%20-%20Bonaire.jpg',
    'br': 'https://www.fairytrail.app/img-assets/postcards/29%20-%20Brazil.jpg',
    'bra': 'https://www.fairytrail.app/img-assets/postcards/29%20-%20Brazil.jpg',
    'brazil': 'https://www.fairytrail.app/img-assets/postcards/29%20-%20Brazil.jpg',
    'brb': 'https://www.fairytrail.app/img-assets/postcards/19%20-%20Barbados.jpg',
    'britain': 'https://www.fairytrail.app/img-assets/postcards/228%20-%20United%20Kingdom.jpg',
    'british indian ocean territory': 'https://www.fairytrail.app/img-assets/postcards/30%20-%20British%20Indian%20Ocean%20Territory.jpg',
    'british virgin islands': 'https://www.fairytrail.app/img-assets/postcards/31%20-%20British%20Virgin%20Islands.jpg',
    'brn': 'https://www.fairytrail.app/img-assets/postcards/32%20-%20Brunei.jpg',
    'brunei': 'https://www.fairytrail.app/img-assets/postcards/32%20-%20Brunei.jpg',
    'bs': 'https://www.fairytrail.app/img-assets/postcards/16%20-%20Bahamas.jpg',
    'bt': 'https://www.fairytrail.app/img-assets/postcards/25%20-%20Bhutan.jpg',
    'btn': 'https://www.fairytrail.app/img-assets/postcards/25%20-%20Bhutan.jpg',
    'bulgaria': 'https://www.fairytrail.app/img-assets/postcards/33%20-%20Bulgaria.jpg',
    'burkina faso': 'https://www.fairytrail.app/img-assets/postcards/34%20-%20Burkina%20Faso.jpg',
    'burma': 'https://www.fairytrail.app/img-assets/postcards/144%20-%20Myanmar.jpg',
    'burundi': 'https://www.fairytrail.app/img-assets/postcards/35%20-%20Burundi.jpg',
    'bw': 'https://www.fairytrail.app/img-assets/postcards/28%20-%20Botswana.jpg',
    'bwa': 'https://www.fairytrail.app/img-assets/postcards/28%20-%20Botswana.jpg',
    'by': 'https://www.fairytrail.app/img-assets/postcards/20%20-%20Belarus.jpg',
    'bz': 'https://www.fairytrail.app/img-assets/postcards/22%20-%20Belize.jpg',
    'ca': 'https://www.fairytrail.app/img-assets/postcards/38%20-%20Canada.jpg',
    'caf': 'https://www.fairytrail.app/img-assets/postcards/41%20-%20Central%20African%20Republic.jpg',
    'cambodia': 'https://www.fairytrail.app/img-assets/postcards/36%20-%20Cambodia.jpg',
    'cameroon': 'https://www.fairytrail.app/img-assets/postcards/37%20-%20Cameroon.jpg',
    'can': 'https://www.fairytrail.app/img-assets/postcards/38%20-%20Canada.jpg',
    'canada': 'https://www.fairytrail.app/img-assets/postcards/38%20-%20Canada.jpg',
    'cape verde': 'https://www.fairytrail.app/img-assets/postcards/39%20-%20Cape%20Verde.jpg',
    'cayman islands': 'https://www.fairytrail.app/img-assets/postcards/40%20-%20Cayman%20Islands.jpg',
    'cc': 'https://www.fairytrail.app/img-assets/postcards/46%20-%20Cocos%20Islands.jpg',
    'cck': 'https://www.fairytrail.app/img-assets/postcards/46%20-%20Cocos%20Islands.jpg',
    'cd': 'https://www.fairytrail.app/img-assets/postcards/56%20-%20Democratic%20Republic%20of%20the%20Congo.jpg',
    'central african republic': 'https://www.fairytrail.app/img-assets/postcards/41%20-%20Central%20African%20Republic.jpg',
    'cf': 'https://www.fairytrail.app/img-assets/postcards/41%20-%20Central%20African%20Republic.jpg',
    'cg': 'https://www.fairytrail.app/img-assets/postcards/173%20-%20Republic%20of%20the%20Congo.jpg',
    'ch': 'https://www.fairytrail.app/img-assets/postcards/209%20-%20Switzerland.jpg',
    'chad': 'https://www.fairytrail.app/img-assets/postcards/42%20-%20Chad.jpg',
    'che': 'https://www.fairytrail.app/img-assets/postcards/209%20-%20Switzerland.jpg',
    'chile': 'https://www.fairytrail.app/img-assets/postcards/43%20-%20Chile.jpg',
    'china': 'https://www.fairytrail.app/img-assets/postcards/44%20-%20China.jpg',
    'chl': 'https://www.fairytrail.app/img-assets/postcards/43%20-%20Chile.jpg',
    'chn': 'https://www.fairytrail.app/img-assets/postcards/44%20-%20China.jpg',
    'christmas island': 'https://www.fairytrail.app/img-assets/postcards/45%20-%20Christmas%20Island.jpg',
    'ci': 'https://www.fairytrail.app/img-assets/postcards/103%20-%20Ivory%20Coast.jpg',
    'civ': 'https://www.fairytrail.app/img-assets/postcards/103%20-%20Ivory%20Coast.jpg',
    'ck': 'https://www.fairytrail.app/img-assets/postcards/49%20-%20Cook%20Islands.jpg',
    'cl': 'https://www.fairytrail.app/img-assets/postcards/43%20-%20Chile.jpg',
    'cm': 'https://www.fairytrail.app/img-assets/postcards/37%20-%20Cameroon.jpg',
    'cmr': 'https://www.fairytrail.app/img-assets/postcards/37%20-%20Cameroon.jpg',
    'cn': 'https://www.fairytrail.app/img-assets/postcards/44%20-%20China.jpg',
    'co': 'https://www.fairytrail.app/img-assets/postcards/47%20-%20Colombia.jpg',
    'cocos islands': 'https://www.fairytrail.app/img-assets/postcards/46%20-%20Cocos%20Islands.jpg',
    'cod': 'https://www.fairytrail.app/img-assets/postcards/56%20-%20Democratic%20Republic%20of%20the%20Congo.jpg',
    'cog': 'https://www.fairytrail.app/img-assets/postcards/173%20-%20Republic%20of%20the%20Congo.jpg',
    'cok': 'https://www.fairytrail.app/img-assets/postcards/49%20-%20Cook%20Islands.jpg',
    'col': 'https://www.fairytrail.app/img-assets/postcards/47%20-%20Colombia.jpg',
    'colombia': 'https://www.fairytrail.app/img-assets/postcards/47%20-%20Colombia.jpg',
    'com': 'https://www.fairytrail.app/img-assets/postcards/48%20-%20Comoros.jpg',
    'comoros': 'https://www.fairytrail.app/img-assets/postcards/48%20-%20Comoros.jpg',
    'congo': 'https://www.fairytrail.app/img-assets/postcards/173%20-%20Republic%20of%20the%20Congo.jpg',
    'congo-brazzaville': 'https://www.fairytrail.app/img-assets/postcards/173%20-%20Republic%20of%20the%20Congo.jpg',
    'congo-kinshasa': 'https://www.fairytrail.app/img-assets/postcards/56%20-%20Democratic%20Republic%20of%20the%20Congo.jpg',
    'cook islands': 'https://www.fairytrail.app/img-assets/postcards/49%20-%20Cook%20Islands.jpg',
    'costa rica': 'https://www.fairytrail.app/img-assets/postcards/50%20-%20Costa%20Rica.jpg',
    'cote d\'ivoire': 'https://www.fairytrail.app/img-assets/postcards/103%20-%20Ivory%20Coast.jpg',
    'cote divoire': 'https://www.fairytrail.app/img-assets/postcards/103%20-%20Ivory%20Coast.jpg',
    'cpv': 'https://www.fairytrail.app/img-assets/postcards/39%20-%20Cape%20Verde.jpg',
    'cr': 'https://www.fairytrail.app/img-assets/postcards/50%20-%20Costa%20Rica.jpg',
    'cri': 'https://www.fairytrail.app/img-assets/postcards/50%20-%20Costa%20Rica.jpg',
    'croatia': 'https://www.fairytrail.app/img-assets/postcards/51%20-%20Croatia.jpg',
    'cu': 'https://www.fairytrail.app/img-assets/postcards/52%20-%20Cuba.jpg',
    'cub': 'https://www.fairytrail.app/img-assets/postcards/52%20-%20Cuba.jpg',
    'cuba': 'https://www.fairytrail.app/img-assets/postcards/52%20-%20Cuba.jpg',
    'curacao': 'https://www.fairytrail.app/img-assets/postcards/53%20-%20Curacao.jpg',
    'cuw': 'https://www.fairytrail.app/img-assets/postcards/53%20-%20Curacao.jpg',
    'cv': 'https://www.fairytrail.app/img-assets/postcards/39%20-%20Cape%20Verde.jpg',
    'cw': 'https://www.fairytrail.app/img-assets/postcards/53%20-%20Curacao.jpg',
    'cx': 'https://www.fairytrail.app/img-assets/postcards/45%20-%20Christmas%20Island.jpg',
    'cxr': 'https://www.fairytrail.app/img-assets/postcards/45%20-%20Christmas%20Island.jpg',
    'cy': 'https://www.fairytrail.app/img-assets/postcards/54%20-%20Cyprus.jpg',
    'cym': 'https://www.fairytrail.app/img-assets/postcards/40%20-%20Cayman%20Islands.jpg',
    'cyp': 'https://www.fairytrail.app/img-assets/postcards/54%20-%20Cyprus.jpg',
    'cyprus': 'https://www.fairytrail.app/img-assets/postcards/54%20-%20Cyprus.jpg',
    'cz': 'https://www.fairytrail.app/img-assets/postcards/55%20-%20Czech%20Republic.jpg',
    'cze': 'https://www.fairytrail.app/img-assets/postcards/55%20-%20Czech%20Republic.jpg',
    'czech republic': 'https://www.fairytrail.app/img-assets/postcards/55%20-%20Czech%20Republic.jpg',
    'czechia': 'https://www.fairytrail.app/img-assets/postcards/55%20-%20Czech%20Republic.jpg',
    'côte d\'ivoire': 'https://www.fairytrail.app/img-assets/postcards/103%20-%20Ivory%20Coast.jpg',
    'de': 'https://www.fairytrail.app/img-assets/postcards/78%20-%20Germany.jpg',
    'democratic republic of the congo': 'https://www.fairytrail.app/img-assets/postcards/56%20-%20Democratic%20Republic%20of%20the%20Congo.jpg',
    'denmark': 'https://www.fairytrail.app/img-assets/postcards/57%20-%20Denmark.jpg',
    'deu': 'https://www.fairytrail.app/img-assets/postcards/78%20-%20Germany.jpg',
    'dj': 'https://www.fairytrail.app/img-assets/postcards/58%20-%20Djibouti.jpg',
    'dji': 'https://www.fairytrail.app/img-assets/postcards/58%20-%20Djibouti.jpg',
    'djibouti': 'https://www.fairytrail.app/img-assets/postcards/58%20-%20Djibouti.jpg',
    'dk': 'https://www.fairytrail.app/img-assets/postcards/57%20-%20Denmark.jpg',
    'dm': 'https://www.fairytrail.app/img-assets/postcards/59%20-%20Dominica.jpg',
    'dma': 'https://www.fairytrail.app/img-assets/postcards/59%20-%20Dominica.jpg',
    'dnk': 'https://www.fairytrail.app/img-assets/postcards/57%20-%20Denmark.jpg',
    'do': 'https://www.fairytrail.app/img-assets/postcards/60%20-%20Dominican%20Republic.jpg',
    'dom': 'https://www.fairytrail.app/img-assets/postcards/60%20-%20Dominican%20Republic.jpg',
    'dominica': 'https://www.fairytrail.app/img-assets/postcards/59%20-%20Dominica.jpg',
    'dominican republic': 'https://www.fairytrail.app/img-assets/postcards/60%20-%20Dominican%20Republic.jpg',
    'dprk': 'https://www.fairytrail.app/img-assets/postcards/156%20-%20North%20Korea.jpg',
    'dr congo': 'https://www.fairytrail.app/img-assets/postcards/56%20-%20Democratic%20Republic%20of%20the%20Congo.jpg',
    'drc': 'https://www.fairytrail.app/img-assets/postcards/56%20-%20Democratic%20Republic%20of%20the%20Congo.jpg',
    'dz': 'https://www.fairytrail.app/img-assets/postcards/3%20-%20Algeria.jpg',
    'dza': 'https://www.fairytrail.app/img-assets/postcards/3%20-%20Algeria.jpg',
    'east timor': 'https://www.fairytrail.app/img-assets/postcards/61%20-%20East%20Timor.jpg',
    'ec': 'https://www.fairytrail.app/img-assets/postcards/62%20-%20Ecuador.jpg',
    'ecu': 'https://www.fairytrail.app/img-assets/postcards/62%20-%20Ecuador.jpg',
    'ecuador': 'https://www.fairytrail.app/img-assets/postcards/62%20-%20Ecuador.jpg',
    'ee': 'https://www.fairytrail.app/img-assets/postcards/67%20-%20Estonia.jpg',
    'eg': 'https://www.fairytrail.app/img-assets/postcards/63%20-%20Egypt.jpg',
    'egy': 'https://www.fairytrail.app/img-assets/postcards/63%20-%20Egypt.jpg',
    'egypt': 'https://www.fairytrail.app/img-assets/postcards/63%20-%20Egypt.jpg',
    'eh': 'https://www.fairytrail.app/img-assets/postcards/237%20-%20Western%20Sahara.jpg',
    'el salvador': 'https://www.fairytrail.app/img-assets/postcards/64%20-%20El%20Salvador.jpg',
    'england': 'https://www.fairytrail.app/img-assets/postcards/228%20-%20United%20Kingdom.jpg',
    'equatorial guinea': 'https://www.fairytrail.app/img-assets/postcards/65%20-%20Equatorial%20Guinea.jpg',
    'er': 'https://www.fairytrail.app/img-assets/postcards/66%20-%20Eritrea.jpg',
    'eri': 'https://www.fairytrail.app/img-assets/postcards/66%20-%20Eritrea.jpg',
    'eritrea': 'https://www.fairytrail.app/img-assets/postcards/66%20-%20Eritrea.jpg',
    'es': 'https://www.fairytrail.app/img-assets/postcards/202%20-%20Spain.jpg',
    'esh': 'https://www.fairytrail.app/img-assets/postcards/237%20-%20Western%20Sahara.jpg',
    'esp': 'https://www.fairytrail.app/img-assets/postcards/202%20-%20Spain.jpg',
    'est': 'https://www.fairytrail.app/img-assets/postcards/67%20-%20Estonia.jpg',
    'estonia': 'https://www.fairytrail.app/img-assets/postcards/67%20-%20Estonia.jpg',
    'eswatini': 'https://www.fairytrail.app/img-assets/postcards/207%20-%20Swaziland.jpg',
    'et': 'https://www.fairytrail.app/img-assets/postcards/68%20-%20Ethiopia.jpg',
    'eth': 'https://www.fairytrail.app/img-assets/postcards/68%20-%20Ethiopia.jpg',
    'ethiopia': 'https://www.fairytrail.app/img-assets/postcards/68%20-%20Ethiopia.jpg',
    'falkland islands': 'https://www.fairytrail.app/img-assets/postcards/69%20-%20Falkland%20Islands.jpg',
    'faroe islands': 'https://www.fairytrail.app/img-assets/postcards/70%20-%20Faroe%20Islands.jpg',
    'fi': 'https://www.fairytrail.app/img-assets/postcards/72%20-%20Finland.jpg',
    'fiji': 'https://www.fairytrail.app/img-assets/postcards/71%20-%20Fiji.jpg',
    'fin': 'https://www.fairytrail.app/img-assets/postcards/72%20-%20Finland.jpg',
    'finland': 'https://www.fairytrail.app/img-assets/postcards/72%20-%20Finland.jpg',
    'fj': 'https://www.fairytrail.app/img-assets/postcards/71%20-%20Fiji.jpg',
    'fji': 'https://www.fairytrail.app/img-assets/postcards/71%20-%20Fiji.jpg',
    'fk': 'https://www.fairytrail.app/img-assets/postcards/69%20-%20Falkland%20Islands.jpg',
    'flk': 'https://www.fairytrail.app/img-assets/postcards/69%20-%20Falkland%20Islands.jpg',
    'fm': 'https://www.fairytrail.app/img-assets/postcards/136%20-%20Micronesia.jpg',
    'fo': 'https://www.fairytrail.app/img-assets/postcards/70%20-%20Faroe%20Islands.jpg',
    'fr': 'https://www.fairytrail.app/img-assets/postcards/73%20-%20France.jpg',
    'fra': 'https://www.fairytrail.app/img-assets/postcards/73%20-%20France.jpg',
    'france': 'https://www.fairytrail.app/img-assets/postcards/73%20-%20France.jpg',
    'french polynesia': 'https://www.fairytrail.app/img-assets/postcards/74%20-%20French%20Polynesia.jpg',
    'fro': 'https://www.fairytrail.app/img-assets/postcards/70%20-%20Faroe%20Islands.jpg',
    'fsm': 'https://www.fairytrail.app/img-assets/postcards/136%20-%20Micronesia.jpg',
    'fyrom': 'https://www.fairytrail.app/img-assets/postcards/124%20-%20Macedonia.jpg',
    'ga': 'https://www.fairytrail.app/img-assets/postcards/75%20-%20Gabon.jpg',
    'gab': 'https://www.fairytrail.app/img-assets/postcards/75%20-%20Gabon.jpg',
    'gabon': 'https://www.fairytrail.app/img-assets/postcards/75%20-%20Gabon.jpg',
    'gambia': 'https://www.fairytrail.app/img-assets/postcards/76%20-%20Gambia.jpg',
    'gb': 'https://www.fairytrail.app/img-assets/postcards/228%20-%20United%20Kingdom.jpg',
    'gbr': 'https://www.fairytrail.app/img-assets/postcards/228%20-%20United%20Kingdom.jpg',
    'gd': 'https://www.fairytrail.app/img-assets/postcards/83%20-%20Grenada.jpg',
    'ge': 'https://www.fairytrail.app/img-assets/postcards/77%20-%20Georgia.jpg',
    'geo': 'https://www.fairytrail.app/img-assets/postcards/77%20-%20Georgia.jpg',
    'georgia': 'https://www.fairytrail.app/img-assets/postcards/77%20-%20Georgia.jpg',
    'germany': 'https://www.fairytrail.app/img-assets/postcards/78%20-%20Germany.jpg',
    'gg': 'https://www.fairytrail.app/img-assets/postcards/86%20-%20Guernsey.jpg',
    'ggy': 'https://www.fairytrail.app/img-assets/postcards/86%20-%20Guernsey.jpg',
    'gh': 'https://www.fairytrail.app/img-assets/postcards/79%20-%20Ghana.jpg',
    'gha': 'https://www.fairytrail.app/img-assets/postcards/79%20-%20Ghana.jpg',
    'ghana': 'https://www.fairytrail.app/img-assets/postcards/79%20-%20Ghana.jpg',
    'gi': 'https://www.fairytrail.app/img-assets/postcards/80%20-%20Gibraltar.jpg',
    'gib': 'https://www.fairytrail.app/img-assets/postcards/80%20-%20Gibraltar.jpg',
    'gibraltar': 'https://www.fairytrail.app/img-assets/postcards/80%20-%20Gibraltar.jpg',
    'gin': 'https://www.fairytrail.app/img-assets/postcards/87%20-%20Guinea.jpg',
    'gl': 'https://www.fairytrail.app/img-assets/postcards/82%20-%20Greenland.jpg',
    'gm': 'https://www.fairytrail.app/img-assets/postcards/76%20-%20Gambia.jpg',
    'gmb': 'https://www.fairytrail.app/img-assets/postcards/76%20-%20Gambia.jpg',
    'gn': 'https://www.fairytrail.app/img-assets/postcards/87%20-%20Guinea.jpg',
    'gnb': 'https://www.fairytrail.app/img-assets/postcards/88%20-%20Guinea-Bissau.jpg',
    'gnq': 'https://www.fairytrail.app/img-assets/postcards/65%20-%20Equatorial%20Guinea.jpg',
    'gp': 'https://www.fairytrail.app/img-assets/postcards/243%20-%20Guadeloupe.jpg',
    'gq': 'https://www.fairytrail.app/img-assets/postcards/65%20-%20Equatorial%20Guinea.jpg',
    'gr': 'https://www.fairytrail.app/img-assets/postcards/81%20-%20Greece.jpg',
    'grc': 'https://www.fairytrail.app/img-assets/postcards/81%20-%20Greece.jpg',
    'grd': 'https://www.fairytrail.app/img-assets/postcards/83%20-%20Grenada.jpg',
    'great britain': 'https://www.fairytrail.app/img-assets/postcards/228%20-%20United%20Kingdom.jpg',
    'greece': 'https://www.fairytrail.app/img-assets/postcards/81%20-%20Greece.jpg',
    'greenland': 'https://www.fairytrail.app/img-assets/postcards/82%20-%20Greenland.jpg',
    'grenada': 'https://www.fairytrail.app/img-assets/postcards/83%20-%20Grenada.jpg',
    'grl': 'https://www.fairytrail.app/img-assets/postcards/82%20-%20Greenland.jpg',
    'gt': 'https://www.fairytrail.app/img-assets/postcards/85%20-%20Guatemala.jpg',
    'gtm': 'https://www.fairytrail.app/img-assets/postcards/85%20-%20Guatemala.jpg',
    'gu': 'https://www.fairytrail.app/img-assets/postcards/84%20-%20Guam.jpg',
    'guadeloupe': 'https://www.fairytrail.app/img-assets/postcards/243%20-%20Guadeloupe.jpg',
    'guam': 'https://www.fairytrail.app/img-assets/postcards/84%20-%20Guam.jpg',
    'guatemala': 'https://www.fairytrail.app/img-assets/postcards/85%20-%20Guatemala.jpg',
    'guernsey': 'https://www.fairytrail.app/img-assets/postcards/86%20-%20Guernsey.jpg',
    'guinea': 'https://www.fairytrail.app/img-assets/postcards/87%20-%20Guinea.jpg',
    'guinea bissau': 'https://www.fairytrail.app/img-assets/postcards/88%20-%20Guinea-Bissau.jpg',
    'guinea-bissau': 'https://www.fairytrail.app/img-assets/postcards/88%20-%20Guinea-Bissau.jpg',
    'gum': 'https://www.fairytrail.app/img-assets/postcards/84%20-%20Guam.jpg',
    'guy': 'https://www.fairytrail.app/img-assets/postcards/89%20-%20Guyana.jpg',
    'guyana': 'https://www.fairytrail.app/img-assets/postcards/89%20-%20Guyana.jpg',
    'gw': 'https://www.fairytrail.app/img-assets/postcards/88%20-%20Guinea-Bissau.jpg',
    'gy': 'https://www.fairytrail.app/img-assets/postcards/89%20-%20Guyana.jpg',
    'haiti': 'https://www.fairytrail.app/img-assets/postcards/90%20-%20Haiti.jpg',
    'hk': 'https://www.fairytrail.app/img-assets/postcards/92%20-%20Hong%20Kong.jpg',
    'hkg': 'https://www.fairytrail.app/img-assets/postcards/92%20-%20Hong%20Kong.jpg',
    'hn': 'https://www.fairytrail.app/img-assets/postcards/91%20-%20Honduras.jpg',
    'hnd': 'https://www.fairytrail.app/img-assets/postcards/91%20-%20Honduras.jpg',
    'holland': 'https://www.fairytrail.app/img-assets/postcards/148%20-%20Netherlands.jpg',
    'holy see': 'https://www.fairytrail.app/img-assets/postcards/233%20-%20Vatican.jpg',
    'honduras': 'https://www.fairytrail.app/img-assets/postcards/91%20-%20Honduras.jpg',
    'hong kong': 'https://www.fairytrail.app/img-assets/postcards/92%20-%20Hong%20Kong.jpg',
    'hr': 'https://www.fairytrail.app/img-assets/postcards/51%20-%20Croatia.jpg',
    'hrv': 'https://www.fairytrail.app/img-assets/postcards/51%20-%20Croatia.jpg',
    'ht': 'https://www.fairytrail.app/img-assets/postcards/90%20-%20Haiti.jpg',
    'hti': 'https://www.fairytrail.app/img-assets/postcards/90%20-%20Haiti.jpg',
    'hu': 'https://www.fairytrail.app/img-assets/postcards/93%20-%20Hungary.jpg',
    'hun': 'https://www.fairytrail.app/img-assets/postcards/93%20-%20Hungary.jpg',
    'hungary': 'https://www.fairytrail.app/img-assets/postcards/93%20-%20Hungary.jpg',
    'iceland': 'https://www.fairytrail.app/img-assets/postcards/94%20-%20Iceland.jpg',
    'id': 'https://www.fairytrail.app/img-assets/postcards/96%20-%20Indonesia.jpg',
    'idn': 'https://www.fairytrail.app/img-assets/postcards/96%20-%20Indonesia.jpg',
    'ie': 'https://www.fairytrail.app/img-assets/postcards/99%20-%20Ireland.jpg',
    'il': 'https://www.fairytrail.app/img-assets/postcards/101%20-%20Israel.jpg',
    'im': 'https://www.fairytrail.app/img-assets/postcards/100%20-%20Isle%20of%20Man.jpg',
    'imn': 'https://www.fairytrail.app/img-assets/postcards/100%20-%20Isle%20of%20Man.jpg',
    'in': 'https://www.fairytrail.app/img-assets/postcards/95%20-%20India.jpg',
    'ind': 'https://www.fairytrail.app/img-assets/postcards/95%20-%20India.jpg',
    'india': 'https://www.fairytrail.app/img-assets/postcards/95%20-%20India.jpg',
    'indonesia': 'https://www.fairytrail.app/img-assets/postcards/96%20-%20Indonesia.jpg',
    'io': 'https://www.fairytrail.app/img-assets/postcards/30%20-%20British%20Indian%20Ocean%20Territory.jpg',
    'iot': 'https://www.fairytrail.app/img-assets/postcards/30%20-%20British%20Indian%20Ocean%20Territory.jpg',
    'iq': 'https://www.fairytrail.app/img-assets/postcards/98%20-%20Iraq.jpg',
    'ir': 'https://www.fairytrail.app/img-assets/postcards/97%20-%20Iran.jpg',
    'iran': 'https://www.fairytrail.app/img-assets/postcards/97%20-%20Iran.jpg',
    'iraq': 'https://www.fairytrail.app/img-assets/postcards/98%20-%20Iraq.jpg',
    'ireland': 'https://www.fairytrail.app/img-assets/postcards/99%20-%20Ireland.jpg',
    'irl': 'https://www.fairytrail.app/img-assets/postcards/99%20-%20Ireland.jpg',
    'irn': 'https://www.fairytrail.app/img-assets/postcards/97%20-%20Iran.jpg',
    'irq': 'https://www.fairytrail.app/img-assets/postcards/98%20-%20Iraq.jpg',
    'is': 'https://www.fairytrail.app/img-assets/postcards/94%20-%20Iceland.jpg',
    'isl': 'https://www.fairytrail.app/img-assets/postcards/94%20-%20Iceland.jpg',
    'isle of man': 'https://www.fairytrail.app/img-assets/postcards/100%20-%20Isle%20of%20Man.jpg',
    'isr': 'https://www.fairytrail.app/img-assets/postcards/101%20-%20Israel.jpg',
    'israel': 'https://www.fairytrail.app/img-assets/postcards/101%20-%20Israel.jpg',
    'it': 'https://www.fairytrail.app/img-assets/postcards/102%20-%20Italy.jpg',
    'ita': 'https://www.fairytrail.app/img-assets/postcards/102%20-%20Italy.jpg',
    'italy': 'https://www.fairytrail.app/img-assets/postcards/102%20-%20Italy.jpg',
    'ivory coast': 'https://www.fairytrail.app/img-assets/postcards/103%20-%20Ivory%20Coast.jpg',
    'jam': 'https://www.fairytrail.app/img-assets/postcards/104%20-%20Jamaica.jpg',
    'jamaica': 'https://www.fairytrail.app/img-assets/postcards/104%20-%20Jamaica.jpg',
    'japan': 'https://www.fairytrail.app/img-assets/postcards/105%20-%20Japan.jpg',
    'je': 'https://www.fairytrail.app/img-assets/postcards/106%20-%20Jersey.jpg',
    'jersey': 'https://www.fairytrail.app/img-assets/postcards/106%20-%20Jersey.jpg',
    'jey': 'https://www.fairytrail.app/img-assets/postcards/106%20-%20Jersey.jpg',
    'jm': 'https://www.fairytrail.app/img-assets/postcards/104%20-%20Jamaica.jpg',
    'jo': 'https://www.fairytrail.app/img-assets/postcards/107%20-%20Jordan.jpg',
    'jor': 'https://www.fairytrail.app/img-assets/postcards/107%20-%20Jordan.jpg',
    'jordan': 'https://www.fairytrail.app/img-assets/postcards/107%20-%20Jordan.jpg',
    'jp': 'https://www.fairytrail.app/img-assets/postcards/105%20-%20Japan.jpg',
    'jpn': 'https://www.fairytrail.app/img-assets/postcards/105%20-%20Japan.jpg',
    'kaz': 'https://www.fairytrail.app/img-assets/postcards/108%20-%20Kazakhstan.jpg',
    'kazakhstan': 'https://www.fairytrail.app/img-assets/postcards/108%20-%20Kazakhstan.jpg',
    'ke': 'https://www.fairytrail.app/img-assets/postcards/109%20-%20Kenya.jpg',
    'ken': 'https://www.fairytrail.app/img-assets/postcards/109%20-%20Kenya.jpg',
    'kenya': 'https://www.fairytrail.app/img-assets/postcards/109%20-%20Kenya.jpg',
    'kg': 'https://www.fairytrail.app/img-assets/postcards/113%20-%20Kyrgyzstan.jpg',
    'kgz': 'https://www.fairytrail.app/img-assets/postcards/113%20-%20Kyrgyzstan.jpg',
    'kh': 'https://www.fairytrail.app/img-assets/postcards/36%20-%20Cambodia.jpg',
    'khm': 'https://www.fairytrail.app/img-assets/postcards/36%20-%20Cambodia.jpg',
    'ki': 'https://www.fairytrail.app/img-assets/postcards/110%20-%20Kiribati.jpg',
    'kir': 'https://www.fairytrail.app/img-assets/postcards/110%20-%20Kiribati.jpg',
    'kiribati': 'https://www.fairytrail.app/img-assets/postcards/110%20-%20Kiribati.jpg',
    'km': 'https://www.fairytrail.app/img-assets/postcards/48%20-%20Comoros.jpg',
    'kn': 'https://www.fairytrail.app/img-assets/postcards/180%20-%20Saint%20Kitts%20and%20Nevis.jpg',
    'kna': 'https://www.fairytrail.app/img-assets/postcards/180%20-%20Saint%20Kitts%20and%20Nevis.jpg',
    'kor': 'https://www.fairytrail.app/img-assets/postcards/200%20-%20South%20Korea.jpg',
    'kosovo': 'https://www.fairytrail.app/img-assets/postcards/111%20-%20Kosovo.jpg',
    'kp': 'https://www.fairytrail.app/img-assets/postcards/156%20-%20North%20Korea.jpg',
    'kr': 'https://www.fairytrail.app/img-assets/postcards/200%20-%20South%20Korea.jpg',
    'kuwait': 'https://www.fairytrail.app/img-assets/postcards/112%20-%20Kuwait.jpg',
    'kw': 'https://www.fairytrail.app/img-assets/postcards/112%20-%20Kuwait.jpg',
    'kwt': 'https://www.fairytrail.app/img-assets/postcards/112%20-%20Kuwait.jpg',
    'ky': 'https://www.fairytrail.app/img-assets/postcards/40%20-%20Cayman%20Islands.jpg',
    'kyrgyzstan': 'https://www.fairytrail.app/img-assets/postcards/113%20-%20Kyrgyzstan.jpg',
    'kz': 'https://www.fairytrail.app/img-assets/postcards/108%20-%20Kazakhstan.jpg',
    'la': 'https://www.fairytrail.app/img-assets/postcards/114%20-%20Laos.jpg',
    'lao': 'https://www.fairytrail.app/img-assets/postcards/114%20-%20Laos.jpg',
    'laos': 'https://www.fairytrail.app/img-assets/postcards/114%20-%20Laos.jpg',
    'latvia': 'https://www.fairytrail.app/img-assets/postcards/115%20-%20Latvia.jpg',
    'lb': 'https://www.fairytrail.app/img-assets/postcards/116%20-%20Lebanon.jpg',
    'lbn': 'https://www.fairytrail.app/img-assets/postcards/116%20-%20Lebanon.jpg',
    'lbr': 'https://www.fairytrail.app/img-assets/postcards/118%20-%20Liberia.jpg',
    'lby': 'https://www.fairytrail.app/img-assets/postcards/119%20-%20Libya.jpg',
    'lc': 'https://www.fairytrail.app/img-assets/postcards/181%20-%20Saint%20Lucia.jpg',
    'lca': 'https://www.fairytrail.app/img-assets/postcards/181%20-%20Saint%20Lucia.jpg',
    'lebanon': 'https://www.fairytrail.app/img-assets/postcards/116%20-%20Lebanon.jpg',
    'lesotho': 'https://www.fairytrail.app/img-assets/postcards/117%20-%20Lesotho.jpg',
    'li': 'https://www.fairytrail.app/img-assets/postcards/120%20-%20Liechtenstein.jpg',
    'liberia': 'https://www.fairytrail.app/img-assets/postcards/118%20-%20Liberia.jpg',
    'libya': 'https://www.fairytrail.app/img-assets/postcards/119%20-%20Libya.jpg',
    'lie': 'https://www.fairytrail.app/img-assets/postcards/120%20-%20Liechtenstein.jpg',
    'liechtenstein': 'https://www.fairytrail.app/img-assets/postcards/120%20-%20Liechtenstein.jpg',
    'lithuania': 'https://www.fairytrail.app/img-assets/postcards/121%20-%20Lithuania.jpg',
    'lk': 'https://www.fairytrail.app/img-assets/postcards/203%20-%20Sri%20Lanka.jpg',
    'lka': 'https://www.fairytrail.app/img-assets/postcards/203%20-%20Sri%20Lanka.jpg',
    'lr': 'https://www.fairytrail.app/img-assets/postcards/118%20-%20Liberia.jpg',
    'ls': 'https://www.fairytrail.app/img-assets/postcards/117%20-%20Lesotho.jpg',
    'lso': 'https://www.fairytrail.app/img-assets/postcards/117%20-%20Lesotho.jpg',
    'lt': 'https://www.fairytrail.app/img-assets/postcards/121%20-%20Lithuania.jpg',
    'ltu': 'https://www.fairytrail.app/img-assets/postcards/121%20-%20Lithuania.jpg',
    'lu': 'https://www.fairytrail.app/img-assets/postcards/122%20-%20Luxembourg.jpg',
    'lux': 'https://www.fairytrail.app/img-assets/postcards/122%20-%20Luxembourg.jpg',
    'luxembourg': 'https://www.fairytrail.app/img-assets/postcards/122%20-%20Luxembourg.jpg',
    'lv': 'https://www.fairytrail.app/img-assets/postcards/115%20-%20Latvia.jpg',
    'lva': 'https://www.fairytrail.app/img-assets/postcards/115%20-%20Latvia.jpg',
    'ly': 'https://www.fairytrail.app/img-assets/postcards/119%20-%20Libya.jpg',
    'ma': 'https://www.fairytrail.app/img-assets/postcards/142%20-%20Morocco.jpg',
    'mac': 'https://www.fairytrail.app/img-assets/postcards/123%20-%20Macau.jpg',
    'macao': 'https://www.fairytrail.app/img-assets/postcards/123%20-%20Macau.jpg',
    'macau': 'https://www.fairytrail.app/img-assets/postcards/123%20-%20Macau.jpg',
    'macedonia': 'https://www.fairytrail.app/img-assets/postcards/124%20-%20Macedonia.jpg',
    'madagascar': 'https://www.fairytrail.app/img-assets/postcards/125%20-%20Madagascar.jpg',
    'maf': 'https://www.fairytrail.app/img-assets/postcards/182%20-%20Saint%20Martin.jpg',
    'malawi': 'https://www.fairytrail.app/img-assets/postcards/126%20-%20Malawi.jpg',
    'malaysia': 'https://www.fairytrail.app/img-assets/postcards/127%20-%20Malaysia.jpg',
    'maldives': 'https://www.fairytrail.app/img-assets/postcards/128%20-%20Maldives.jpg',
    'mali': 'https://www.fairytrail.app/img-assets/postcards/129%20-%20Mali.jpg',
    'malta': 'https://www.fairytrail.app/img-assets/postcards/130%20-%20Malta.jpg',
    'mar': 'https://www.fairytrail.app/img-assets/postcards/142%20-%20Morocco.jpg',
    'marshall islands': 'https://www.fairytrail.app/img-assets/postcards/131%20-%20Marshall%20Islands.jpg',
    'mauritania': 'https://www.fairytrail.app/img-assets/postcards/132%20-%20Mauritania.jpg',
    'mauritius': 'https://www.fairytrail.app/img-assets/postcards/133%20-%20Mauritius.jpg',
    'mayotte': 'https://www.fairytrail.app/img-assets/postcards/134%20-%20Mayotte.jpg',
    'mc': 'https://www.fairytrail.app/img-assets/postcards/138%20-%20Monaco.jpg',
    'mco': 'https://www.fairytrail.app/img-assets/postcards/138%20-%20Monaco.jpg',
    'md': 'https://www.fairytrail.app/img-assets/postcards/137%20-%20Moldova.jpg',
    'mda': 'https://www.fairytrail.app/img-assets/postcards/137%20-%20Moldova.jpg',
    'mdg': 'https://www.fairytrail.app/img-assets/postcards/125%20-%20Madagascar.jpg',
    'mdv': 'https://www.fairytrail.app/img-assets/postcards/128%20-%20Maldives.jpg',
    'me': 'https://www.fairytrail.app/img-assets/postcards/140%20-%20Montenegro.jpg',
    'mex': 'https://www.fairytrail.app/img-assets/postcards/135%20-%20Mexico.jpg',
    'mexico': 'https://www.fairytrail.app/img-assets/postcards/135%20-%20Mexico.jpg',
    'mf': 'https://www.fairytrail.app/img-assets/postcards/182%20-%20Saint%20Martin.jpg',
    'mg': 'https://www.fairytrail.app/img-assets/postcards/125%20-%20Madagascar.jpg',
    'mh': 'https://www.fairytrail.app/img-assets/postcards/131%20-%20Marshall%20Islands.jpg',
    'mhl': 'https://www.fairytrail.app/img-assets/postcards/131%20-%20Marshall%20Islands.jpg',
    'micronesia': 'https://www.fairytrail.app/img-assets/postcards/136%20-%20Micronesia.jpg',
    'mk': 'https://www.fairytrail.app/img-assets/postcards/124%20-%20Macedonia.jpg',
    'mkd': 'https://www.fairytrail.app/img-assets/postcards/124%20-%20Macedonia.jpg',
    'ml': 'https://www.fairytrail.app/img-assets/postcards/129%20-%20Mali.jpg',
    'mli': 'https://www.fairytrail.app/img-assets/postcards/129%20-%20Mali.jpg',
    'mlt': 'https://www.fairytrail.app/img-assets/postcards/130%20-%20Malta.jpg',
    'mm': 'https://www.fairytrail.app/img-assets/postcards/144%20-%20Myanmar.jpg',
    'mmr': 'https://www.fairytrail.app/img-assets/postcards/144%20-%20Myanmar.jpg',
    'mn': 'https://www.fairytrail.app/img-assets/postcards/139%20-%20Mongolia.jpg',
    'mne': 'https://www.fairytrail.app/img-assets/postcards/140%20-%20Montenegro.jpg',
    'mng': 'https://www.fairytrail.app/img-assets/postcards/139%20-%20Mongolia.jpg',
    'mnp': 'https://www.fairytrail.app/img-assets/postcards/157%20-%20Northern%20Mariana%20Islands.jpg',
    'mo': 'https://www.fairytrail.app/img-assets/postcards/123%20-%20Macau.jpg',
    'moldova': 'https://www.fairytrail.app/img-assets/postcards/137%20-%20Moldova.jpg',
    'monaco': 'https://www.fairytrail.app/img-assets/postcards/138%20-%20Monaco.jpg',
    'mongolia': 'https://www.fairytrail.app/img-assets/postcards/139%20-%20Mongolia.jpg',
    'montenegro': 'https://www.fairytrail.app/img-assets/postcards/140%20-%20Montenegro.jpg',
    'montserrat': 'https://www.fairytrail.app/img-assets/postcards/141%20-%20Montserrat.jpg',
    'morocco': 'https://www.fairytrail.app/img-assets/postcards/142%20-%20Morocco.jpg',
    'moz': 'https://www.fairytrail.app/img-assets/postcards/143%20-%20Mozambique.jpg',
    'mozambique': 'https://www.fairytrail.app/img-assets/postcards/143%20-%20Mozambique.jpg',
    'mp': 'https://www.fairytrail.app/img-assets/postcards/157%20-%20Northern%20Mariana%20Islands.jpg',
    'mr': 'https://www.fairytrail.app/img-assets/postcards/132%20-%20Mauritania.jpg',
    'mrt': 'https://www.fairytrail.app/img-assets/postcards/132%20-%20Mauritania.jpg',
    'ms': 'https://www.fairytrail.app/img-assets/postcards/141%20-%20Montserrat.jpg',
    'msr': 'https://www.fairytrail.app/img-assets/postcards/141%20-%20Montserrat.jpg',
    'mt': 'https://www.fairytrail.app/img-assets/postcards/130%20-%20Malta.jpg',
    'mu': 'https://www.fairytrail.app/img-assets/postcards/133%20-%20Mauritius.jpg',
    'mus': 'https://www.fairytrail.app/img-assets/postcards/133%20-%20Mauritius.jpg',
    'mv': 'https://www.fairytrail.app/img-assets/postcards/128%20-%20Maldives.jpg',
    'mw': 'https://www.fairytrail.app/img-assets/postcards/126%20-%20Malawi.jpg',
    'mwi': 'https://www.fairytrail.app/img-assets/postcards/126%20-%20Malawi.jpg',
    'mx': 'https://www.fairytrail.app/img-assets/postcards/135%20-%20Mexico.jpg',
    'my': 'https://www.fairytrail.app/img-assets/postcards/127%20-%20Malaysia.jpg',
    'myanmar': 'https://www.fairytrail.app/img-assets/postcards/144%20-%20Myanmar.jpg',
    'mys': 'https://www.fairytrail.app/img-assets/postcards/127%20-%20Malaysia.jpg',
    'myt': 'https://www.fairytrail.app/img-assets/postcards/134%20-%20Mayotte.jpg',
    'mz': 'https://www.fairytrail.app/img-assets/postcards/143%20-%20Mozambique.jpg',
    'na': 'https://www.fairytrail.app/img-assets/postcards/145%20-%20Namibia.jpg',
    'nam': 'https://www.fairytrail.app/img-assets/postcards/145%20-%20Namibia.jpg',
    'namibia': 'https://www.fairytrail.app/img-assets/postcards/145%20-%20Namibia.jpg',
    'nauru': 'https://www.fairytrail.app/img-assets/postcards/146%20-%20Nauru.jpg',
    'nc': 'https://www.fairytrail.app/img-assets/postcards/150%20-%20New%20Caledonia.jpg',
    'ncl': 'https://www.fairytrail.app/img-assets/postcards/150%20-%20New%20Caledonia.jpg',
    'ne': 'https://www.fairytrail.app/img-assets/postcards/153%20-%20Niger.jpg',
    'nepal': 'https://www.fairytrail.app/img-assets/postcards/147%20-%20Nepal.jpg',
    'ner': 'https://www.fairytrail.app/img-assets/postcards/153%20-%20Niger.jpg',
    'netherlands': 'https://www.fairytrail.app/img-assets/postcards/148%20-%20Netherlands.jpg',
    'netherlands antilles': 'https://www.fairytrail.app/img-assets/postcards/149%20-%20Netherlands%20Antilles.jpg',
    'new caledonia': 'https://www.fairytrail.app/img-assets/postcards/150%20-%20New%20Caledonia.jpg',
    'new zealand': 'https://www.fairytrail.app/img-assets/postcards/151%20-%20New%20Zealand.jpg',
    'ng': 'https://www.fairytrail.app/img-assets/postcards/154%20-%20Nigeria.jpg',
    'nga': 'https://www.fairytrail.app/img-assets/postcards/154%20-%20Nigeria.jpg',
    'ni': 'https://www.fairytrail.app/img-assets/postcards/152%20-%20Nicaragua.jpg',
    'nic': 'https://www.fairytrail.app/img-assets/postcards/152%20-%20Nicaragua.jpg',
    'nicaragua': 'https://www.fairytrail.app/img-assets/postcards/152%20-%20Nicaragua.jpg',
    'niger': 'https://www.fairytrail.app/img-assets/postcards/153%20-%20Niger.jpg',
    'nigeria': 'https://www.fairytrail.app/img-assets/postcards/154%20-%20Nigeria.jpg',
    'niu': 'https://www.fairytrail.app/img-assets/postcards/155%20-%20Niue.jpg',
    'niue': 'https://www.fairytrail.app/img-assets/postcards/155%20-%20Niue.jpg',
    'nl': 'https://www.fairytrail.app/img-assets/postcards/148%20-%20Netherlands.jpg',
    'nld': 'https://www.fairytrail.app/img-assets/postcards/148%20-%20Netherlands.jpg',
    'no': 'https://www.fairytrail.app/img-assets/postcards/158%20-%20Norway.jpg',
    'nor': 'https://www.fairytrail.app/img-assets/postcards/158%20-%20Norway.jpg',
    'north korea': 'https://www.fairytrail.app/img-assets/postcards/156%20-%20North%20Korea.jpg',
    'north macedonia': 'https://www.fairytrail.app/img-assets/postcards/124%20-%20Macedonia.jpg',
    'northern mariana islands': 'https://www.fairytrail.app/img-assets/postcards/157%20-%20Northern%20Mariana%20Islands.jpg',
    'norway': 'https://www.fairytrail.app/img-assets/postcards/158%20-%20Norway.jpg',
    'np': 'https://www.fairytrail.app/img-assets/postcards/147%20-%20Nepal.jpg',
    'npl': 'https://www.fairytrail.app/img-assets/postcards/147%20-%20Nepal.jpg',
    'nr': 'https://www.fairytrail.app/img-assets/postcards/146%20-%20Nauru.jpg',
    'nru': 'https://www.fairytrail.app/img-assets/postcards/146%20-%20Nauru.jpg',
    'nu': 'https://www.fairytrail.app/img-assets/postcards/155%20-%20Niue.jpg',
    'nz': 'https://www.fairytrail.app/img-assets/postcards/151%20-%20New%20Zealand.jpg',
    'nzl': 'https://www.fairytrail.app/img-assets/postcards/151%20-%20New%20Zealand.jpg',
    'om': 'https://www.fairytrail.app/img-assets/postcards/159%20-%20Oman.jpg',
    'oman': 'https://www.fairytrail.app/img-assets/postcards/159%20-%20Oman.jpg',
    'omn': 'https://www.fairytrail.app/img-assets/postcards/159%20-%20Oman.jpg',
    'pa': 'https://www.fairytrail.app/img-assets/postcards/163%20-%20Panama.jpg',
    'pak': 'https://www.fairytrail.app/img-assets/postcards/160%20-%20Pakistan.jpg',
    'pakistan': 'https://www.fairytrail.app/img-assets/postcards/160%20-%20Pakistan.jpg',
    'palau': 'https://www.fairytrail.app/img-assets/postcards/161%20-%20Palau.jpg',
    'palestine': 'https://www.fairytrail.app/img-assets/postcards/162%20-%20Palestine.jpg',
    'pan': 'https://www.fairytrail.app/img-assets/postcards/163%20-%20Panama.jpg',
    'panama': 'https://www.fairytrail.app/img-assets/postcards/163%20-%20Panama.jpg',
    'papua new guinea': 'https://www.fairytrail.app/img-assets/postcards/164%20-%20Papua%20New%20Guinea.jpg',
    'paraguay': 'https://www.fairytrail.app/img-assets/postcards/165%20-%20Paraguay.jpg',
    'pcn': 'https://www.fairytrail.app/img-assets/postcards/168%20-%20Pitcairn.jpg',
    'pe': 'https://www.fairytrail.app/img-assets/postcards/166%20-%20Peru.jpg',
    'per': 'https://www.fairytrail.app/img-assets/postcards/166%20-%20Peru.jpg',
    'peru': 'https://www.fairytrail.app/img-assets/postcards/166%20-%20Peru.jpg',
    'pf': 'https://www.fairytrail.app/img-assets/postcards/74%20-%20French%20Polynesia.jpg',
    'pg': 'https://www.fairytrail.app/img-assets/postcards/164%20-%20Papua%20New%20Guinea.jpg',
    'ph': 'https://www.fairytrail.app/img-assets/postcards/167%20-%20Philippines.jpg',
    'philippines': 'https://www.fairytrail.app/img-assets/postcards/167%20-%20Philippines.jpg',
    'phl': 'https://www.fairytrail.app/img-assets/postcards/167%20-%20Philippines.jpg',
    'pitcairn': 'https://www.fairytrail.app/img-assets/postcards/168%20-%20Pitcairn.jpg',
    'pk': 'https://www.fairytrail.app/img-assets/postcards/160%20-%20Pakistan.jpg',
    'pl': 'https://www.fairytrail.app/img-assets/postcards/169%20-%20Poland.jpg',
    'plw': 'https://www.fairytrail.app/img-assets/postcards/161%20-%20Palau.jpg',
    'pm': 'https://www.fairytrail.app/img-assets/postcards/183%20-%20Saint%20Pierre%20and%20Miquelon.jpg',
    'pn': 'https://www.fairytrail.app/img-assets/postcards/168%20-%20Pitcairn.jpg',
    'png': 'https://www.fairytrail.app/img-assets/postcards/164%20-%20Papua%20New%20Guinea.jpg',
    'pol': 'https://www.fairytrail.app/img-assets/postcards/169%20-%20Poland.jpg',
    'poland': 'https://www.fairytrail.app/img-assets/postcards/169%20-%20Poland.jpg',
    'portugal': 'https://www.fairytrail.app/img-assets/postcards/170%20-%20Portugal.jpg',
    'pr': 'https://www.fairytrail.app/img-assets/postcards/171%20-%20Puerto%20Rico.jpg',
    'pri': 'https://www.fairytrail.app/img-assets/postcards/171%20-%20Puerto%20Rico.jpg',
    'prk': 'https://www.fairytrail.app/img-assets/postcards/156%20-%20North%20Korea.jpg',
    'prt': 'https://www.fairytrail.app/img-assets/postcards/170%20-%20Portugal.jpg',
    'pry': 'https://www.fairytrail.app/img-assets/postcards/165%20-%20Paraguay.jpg',
    'ps': 'https://www.fairytrail.app/img-assets/postcards/162%20-%20Palestine.jpg',
    'pse': 'https://www.fairytrail.app/img-assets/postcards/162%20-%20Palestine.jpg',
    'pt': 'https://www.fairytrail.app/img-assets/postcards/170%20-%20Portugal.jpg',
    'puerto rico': 'https://www.fairytrail.app/img-assets/postcards/171%20-%20Puerto%20Rico.jpg',
    'pw': 'https://www.fairytrail.app/img-assets/postcards/161%20-%20Palau.jpg',
    'py': 'https://www.fairytrail.app/img-assets/postcards/165%20-%20Paraguay.jpg',
    'pyf': 'https://www.fairytrail.app/img-assets/postcards/74%20-%20French%20Polynesia.jpg',
    'qa': 'https://www.fairytrail.app/img-assets/postcards/172%20-%20Qatar.jpg',
    'qat': 'https://www.fairytrail.app/img-assets/postcards/172%20-%20Qatar.jpg',
    'qatar': 'https://www.fairytrail.app/img-assets/postcards/172%20-%20Qatar.jpg',
    're': 'https://www.fairytrail.app/img-assets/postcards/174%20-%20Reunion.jpg',
    'republic of korea': 'https://www.fairytrail.app/img-assets/postcards/200%20-%20South%20Korea.jpg',
    'republic of the congo': 'https://www.fairytrail.app/img-assets/postcards/173%20-%20Republic%20of%20the%20Congo.jpg',
    'reu': 'https://www.fairytrail.app/img-assets/postcards/174%20-%20Reunion.jpg',
    'reunion': 'https://www.fairytrail.app/img-assets/postcards/174%20-%20Reunion.jpg',
    'ro': 'https://www.fairytrail.app/img-assets/postcards/175%20-%20Romania.jpg',
    'romania': 'https://www.fairytrail.app/img-assets/postcards/175%20-%20Romania.jpg',
    'rou': 'https://www.fairytrail.app/img-assets/postcards/175%20-%20Romania.jpg',
    'rs': 'https://www.fairytrail.app/img-assets/postcards/190%20-%20Serbia.jpg',
    'ru': 'https://www.fairytrail.app/img-assets/postcards/176%20-%20Russia.jpg',
    'rus': 'https://www.fairytrail.app/img-assets/postcards/176%20-%20Russia.jpg',
    'russia': 'https://www.fairytrail.app/img-assets/postcards/176%20-%20Russia.jpg',
    'russian federation': 'https://www.fairytrail.app/img-assets/postcards/176%20-%20Russia.jpg',
    'rw': 'https://www.fairytrail.app/img-assets/postcards/177%20-%20Rwanda.jpg',
    'rwa': 'https://www.fairytrail.app/img-assets/postcards/177%20-%20Rwanda.jpg',
    'rwanda': 'https://www.fairytrail.app/img-assets/postcards/177%20-%20Rwanda.jpg',
    'sa': 'https://www.fairytrail.app/img-assets/postcards/188%20-%20Saudi%20Arabia.jpg',
    'saint barthelemy': 'https://www.fairytrail.app/img-assets/postcards/178%20-%20Saint%20Barthelemy.jpg',
    'saint helena': 'https://www.fairytrail.app/img-assets/postcards/179%20-%20Saint%20Helena.jpg',
    'saint kitts and nevis': 'https://www.fairytrail.app/img-assets/postcards/180%20-%20Saint%20Kitts%20and%20Nevis.jpg',
    'saint lucia': 'https://www.fairytrail.app/img-assets/postcards/181%20-%20Saint%20Lucia.jpg',
    'saint martin': 'https://www.fairytrail.app/img-assets/postcards/182%20-%20Saint%20Martin.jpg',
    'saint pierre and miquelon': 'https://www.fairytrail.app/img-assets/postcards/183%20-%20Saint%20Pierre%20and%20Miquelon.jpg',
    'saint vincent and the grenadines': 'https://www.fairytrail.app/img-assets/postcards/184%20-%20Saint%20Vincent%20and%20the%20Grenadines.jpg',
    'samoa': 'https://www.fairytrail.app/img-assets/postcards/185%20-%20Samoa.jpg',
    'san marino': 'https://www.fairytrail.app/img-assets/postcards/186%20-%20San%20Marino.jpg',
    'sao tome and principe': 'https://www.fairytrail.app/img-assets/postcards/187%20-%20Sao%20Tome%20and%20Principe.jpg',
    'sau': 'https://www.fairytrail.app/img-assets/postcards/188%20-%20Saudi%20Arabia.jpg',
    'saudi arabia': 'https://www.fairytrail.app/img-assets/postcards/188%20-%20Saudi%20Arabia.jpg',
    'sb': 'https://www.fairytrail.app/img-assets/postcards/197%20-%20Solomon%20Islands.jpg',
    'sc': 'https://www.fairytrail.app/img-assets/postcards/191%20-%20Seychelles.jpg',
    'scotland': 'https://www.fairytrail.app/img-assets/postcards/228%20-%20United%20Kingdom.jpg',
    'sd': 'https://www.fairytrail.app/img-assets/postcards/204%20-%20Sudan.jpg',
    'sdn': 'https://www.fairytrail.app/img-assets/postcards/204%20-%20Sudan.jpg',
    'se': 'https://www.fairytrail.app/img-assets/postcards/208%20-%20Sweden.jpg',
    'sen': 'https://www.fairytrail.app/img-assets/postcards/189%20-%20Senegal.jpg',
    'senegal': 'https://www.fairytrail.app/img-assets/postcards/189%20-%20Senegal.jpg',
    'serbia': 'https://www.fairytrail.app/img-assets/postcards/190%20-%20Serbia.jpg',
    'seychelles': 'https://www.fairytrail.app/img-assets/postcards/191%20-%20Seychelles.jpg',
    'sg': 'https://www.fairytrail.app/img-assets/postcards/193%20-%20Singapore.jpg',
    'sgp': 'https://www.fairytrail.app/img-assets/postcards/193%20-%20Singapore.jpg',
    'sh': 'https://www.fairytrail.app/img-assets/postcards/179%20-%20Saint%20Helena.jpg',
    'shn': 'https://www.fairytrail.app/img-assets/postcards/179%20-%20Saint%20Helena.jpg',
    'si': 'https://www.fairytrail.app/img-assets/postcards/196%20-%20Slovenia.jpg',
    'sierra leone': 'https://www.fairytrail.app/img-assets/postcards/192%20-%20Sierra%20Leone.jpg',
    'singapore': 'https://www.fairytrail.app/img-assets/postcards/193%20-%20Singapore.jpg',
    'sint maarten': 'https://www.fairytrail.app/img-assets/postcards/194%20-%20Sint%20Maarten.jpg',
    'sj': 'https://www.fairytrail.app/img-assets/postcards/206%20-%20Svalbard%20and%20Jan%20Mayen.jpg',
    'sjm': 'https://www.fairytrail.app/img-assets/postcards/206%20-%20Svalbard%20and%20Jan%20Mayen.jpg',
    'sk': 'https://www.fairytrail.app/img-assets/postcards/195%20-%20Slovakia.jpg',
    'sl': 'https://www.fairytrail.app/img-assets/postcards/192%20-%20Sierra%20Leone.jpg',
    'slb': 'https://www.fairytrail.app/img-assets/postcards/197%20-%20Solomon%20Islands.jpg',
    'sle': 'https://www.fairytrail.app/img-assets/postcards/192%20-%20Sierra%20Leone.jpg',
    'slovakia': 'https://www.fairytrail.app/img-assets/postcards/195%20-%20Slovakia.jpg',
    'slovenia': 'https://www.fairytrail.app/img-assets/postcards/196%20-%20Slovenia.jpg',
    'slv': 'https://www.fairytrail.app/img-assets/postcards/64%20-%20El%20Salvador.jpg',
    'sm': 'https://www.fairytrail.app/img-assets/postcards/186%20-%20San%20Marino.jpg',
    'smr': 'https://www.fairytrail.app/img-assets/postcards/186%20-%20San%20Marino.jpg',
    'sn': 'https://www.fairytrail.app/img-assets/postcards/189%20-%20Senegal.jpg',
    'so': 'https://www.fairytrail.app/img-assets/postcards/198%20-%20Somalia.jpg',
    'solomon islands': 'https://www.fairytrail.app/img-assets/postcards/197%20-%20Solomon%20Islands.jpg',
    'som': 'https://www.fairytrail.app/img-assets/postcards/198%20-%20Somalia.jpg',
    'somalia': 'https://www.fairytrail.app/img-assets/postcards/198%20-%20Somalia.jpg',
    'south africa': 'https://www.fairytrail.app/img-assets/postcards/199%20-%20South%20Africa.jpg',
    'south korea': 'https://www.fairytrail.app/img-assets/postcards/200%20-%20South%20Korea.jpg',
    'south sudan': 'https://www.fairytrail.app/img-assets/postcards/201%20-%20South%20Sudan.jpg',
    'spain': 'https://www.fairytrail.app/img-assets/postcards/202%20-%20Spain.jpg',
    'spm': 'https://www.fairytrail.app/img-assets/postcards/183%20-%20Saint%20Pierre%20and%20Miquelon.jpg',
    'sr': 'https://www.fairytrail.app/img-assets/postcards/205%20-%20Suriname.jpg',
    'srb': 'https://www.fairytrail.app/img-assets/postcards/190%20-%20Serbia.jpg',
    'sri lanka': 'https://www.fairytrail.app/img-assets/postcards/203%20-%20Sri%20Lanka.jpg',
    'ss': 'https://www.fairytrail.app/img-assets/postcards/201%20-%20South%20Sudan.jpg',
    'ssd': 'https://www.fairytrail.app/img-assets/postcards/201%20-%20South%20Sudan.jpg',
    'st': 'https://www.fairytrail.app/img-assets/postcards/187%20-%20Sao%20Tome%20and%20Principe.jpg',
    'stp': 'https://www.fairytrail.app/img-assets/postcards/187%20-%20Sao%20Tome%20and%20Principe.jpg',
    'sudan': 'https://www.fairytrail.app/img-assets/postcards/204%20-%20Sudan.jpg',
    'sur': 'https://www.fairytrail.app/img-assets/postcards/205%20-%20Suriname.jpg',
    'suriname': 'https://www.fairytrail.app/img-assets/postcards/205%20-%20Suriname.jpg',
    'sv': 'https://www.fairytrail.app/img-assets/postcards/64%20-%20El%20Salvador.jpg',
    'svalbard and jan mayen': 'https://www.fairytrail.app/img-assets/postcards/206%20-%20Svalbard%20and%20Jan%20Mayen.jpg',
    'svk': 'https://www.fairytrail.app/img-assets/postcards/195%20-%20Slovakia.jpg',
    'svn': 'https://www.fairytrail.app/img-assets/postcards/196%20-%20Slovenia.jpg',
    'swaziland': 'https://www.fairytrail.app/img-assets/postcards/207%20-%20Swaziland.jpg',
    'swe': 'https://www.fairytrail.app/img-assets/postcards/208%20-%20Sweden.jpg',
    'sweden': 'https://www.fairytrail.app/img-assets/postcards/208%20-%20Sweden.jpg',
    'switzerland': 'https://www.fairytrail.app/img-assets/postcards/209%20-%20Switzerland.jpg',
    'swz': 'https://www.fairytrail.app/img-assets/postcards/207%20-%20Swaziland.jpg',
    'sx': 'https://www.fairytrail.app/img-assets/postcards/194%20-%20Sint%20Maarten.jpg',
    'sxm': 'https://www.fairytrail.app/img-assets/postcards/194%20-%20Sint%20Maarten.jpg',
    'sy': 'https://www.fairytrail.app/img-assets/postcards/210%20-%20Syria.jpg',
    'syc': 'https://www.fairytrail.app/img-assets/postcards/191%20-%20Seychelles.jpg',
    'syr': 'https://www.fairytrail.app/img-assets/postcards/210%20-%20Syria.jpg',
    'syria': 'https://www.fairytrail.app/img-assets/postcards/210%20-%20Syria.jpg',
    'sz': 'https://www.fairytrail.app/img-assets/postcards/207%20-%20Swaziland.jpg',
    'taiwan': 'https://www.fairytrail.app/img-assets/postcards/211%20-%20Taiwan.jpg',
    'tajikistan': 'https://www.fairytrail.app/img-assets/postcards/212%20-%20Tajikistan.jpg',
    'tanzania': 'https://www.fairytrail.app/img-assets/postcards/213%20-%20Tanzania.jpg',
    'tc': 'https://www.fairytrail.app/img-assets/postcards/222%20-%20Turks%20and%20Caicos%20Islands.jpg',
    'tca': 'https://www.fairytrail.app/img-assets/postcards/222%20-%20Turks%20and%20Caicos%20Islands.jpg',
    'tcd': 'https://www.fairytrail.app/img-assets/postcards/42%20-%20Chad.jpg',
    'td': 'https://www.fairytrail.app/img-assets/postcards/42%20-%20Chad.jpg',
    'tg': 'https://www.fairytrail.app/img-assets/postcards/215%20-%20Togo.jpg',
    'tgo': 'https://www.fairytrail.app/img-assets/postcards/215%20-%20Togo.jpg',
    'th': 'https://www.fairytrail.app/img-assets/postcards/214%20-%20Thailand.jpg',
    'tha': 'https://www.fairytrail.app/img-assets/postcards/214%20-%20Thailand.jpg',
    'thailand': 'https://www.fairytrail.app/img-assets/postcards/214%20-%20Thailand.jpg',
    'tj': 'https://www.fairytrail.app/img-assets/postcards/212%20-%20Tajikistan.jpg',
    'tjk': 'https://www.fairytrail.app/img-assets/postcards/212%20-%20Tajikistan.jpg',
    'tk': 'https://www.fairytrail.app/img-assets/postcards/216%20-%20Tokelau.jpg',
    'tkl': 'https://www.fairytrail.app/img-assets/postcards/216%20-%20Tokelau.jpg',
    'tkm': 'https://www.fairytrail.app/img-assets/postcards/221%20-%20Turkmenistan.jpg',
    'tl': 'https://www.fairytrail.app/img-assets/postcards/61%20-%20East%20Timor.jpg',
    'tls': 'https://www.fairytrail.app/img-assets/postcards/61%20-%20East%20Timor.jpg',
    'tm': 'https://www.fairytrail.app/img-assets/postcards/221%20-%20Turkmenistan.jpg',
    'tn': 'https://www.fairytrail.app/img-assets/postcards/219%20-%20Tunisia.jpg',
    'to': 'https://www.fairytrail.app/img-assets/postcards/217%20-%20Tonga.jpg',
    'togo': 'https://www.fairytrail.app/img-assets/postcards/215%20-%20Togo.jpg',
    'tokelau': 'https://www.fairytrail.app/img-assets/postcards/216%20-%20Tokelau.jpg',
    'ton': 'https://www.fairytrail.app/img-assets/postcards/217%20-%20Tonga.jpg',
    'tonga': 'https://www.fairytrail.app/img-assets/postcards/217%20-%20Tonga.jpg',
    'tr': 'https://www.fairytrail.app/img-assets/postcards/220%20-%20Turkey.jpg',
    'trinidad and tobago': 'https://www.fairytrail.app/img-assets/postcards/218%20-%20Trinidad%20and%20Tobago.jpg',
    'tt': 'https://www.fairytrail.app/img-assets/postcards/218%20-%20Trinidad%20and%20Tobago.jpg',
    'tto': 'https://www.fairytrail.app/img-assets/postcards/218%20-%20Trinidad%20and%20Tobago.jpg',
    'tun': 'https://www.fairytrail.app/img-assets/postcards/219%20-%20Tunisia.jpg',
    'tunisia': 'https://www.fairytrail.app/img-assets/postcards/219%20-%20Tunisia.jpg',
    'tur': 'https://www.fairytrail.app/img-assets/postcards/220%20-%20Turkey.jpg',
    'turkey': 'https://www.fairytrail.app/img-assets/postcards/220%20-%20Turkey.jpg',
    'turkmenistan': 'https://www.fairytrail.app/img-assets/postcards/221%20-%20Turkmenistan.jpg',
    'turks and caicos islands': 'https://www.fairytrail.app/img-assets/postcards/222%20-%20Turks%20and%20Caicos%20Islands.jpg',
    'tuv': 'https://www.fairytrail.app/img-assets/postcards/223%20-%20Tuvalu.jpg',
    'tuvalu': 'https://www.fairytrail.app/img-assets/postcards/223%20-%20Tuvalu.jpg',
    'tv': 'https://www.fairytrail.app/img-assets/postcards/223%20-%20Tuvalu.jpg',
    'tw': 'https://www.fairytrail.app/img-assets/postcards/211%20-%20Taiwan.jpg',
    'twn': 'https://www.fairytrail.app/img-assets/postcards/211%20-%20Taiwan.jpg',
    'tz': 'https://www.fairytrail.app/img-assets/postcards/213%20-%20Tanzania.jpg',
    'tza': 'https://www.fairytrail.app/img-assets/postcards/213%20-%20Tanzania.jpg',
    'u s virgin islands': 'https://www.fairytrail.app/img-assets/postcards/224%20-%20U.S.%20Virgin%20Islands.jpg',
    'u.s. virgin islands': 'https://www.fairytrail.app/img-assets/postcards/224%20-%20U.S.%20Virgin%20Islands.jpg',
    'ua': 'https://www.fairytrail.app/img-assets/postcards/226%20-%20Ukraine.jpg',
    'uae': 'https://www.fairytrail.app/img-assets/postcards/227%20-%20United%20Arab%20Emirates.jpg',
    'ug': 'https://www.fairytrail.app/img-assets/postcards/225%20-%20Uganda.jpg',
    'uga': 'https://www.fairytrail.app/img-assets/postcards/225%20-%20Uganda.jpg',
    'uganda': 'https://www.fairytrail.app/img-assets/postcards/225%20-%20Uganda.jpg',
    'uk': 'https://www.fairytrail.app/img-assets/postcards/228%20-%20United%20Kingdom.jpg',
    'ukr': 'https://www.fairytrail.app/img-assets/postcards/226%20-%20Ukraine.jpg',
    'ukraine': 'https://www.fairytrail.app/img-assets/postcards/226%20-%20Ukraine.jpg',
    'united arab emirates': 'https://www.fairytrail.app/img-assets/postcards/227%20-%20United%20Arab%20Emirates.jpg',
    'united kingdom': 'https://www.fairytrail.app/img-assets/postcards/228%20-%20United%20Kingdom.jpg',
    'united states': 'https://www.fairytrail.app/img-assets/postcards/229%20-%20United%20States.jpg',
    'united states of america': 'https://www.fairytrail.app/img-assets/postcards/229%20-%20United%20States.jpg',
    'uruguay': 'https://www.fairytrail.app/img-assets/postcards/230%20-%20Uruguay.jpg',
    'ury': 'https://www.fairytrail.app/img-assets/postcards/230%20-%20Uruguay.jpg',
    'us': 'https://www.fairytrail.app/img-assets/postcards/229%20-%20United%20States.jpg',
    'usa': 'https://www.fairytrail.app/img-assets/postcards/229%20-%20United%20States.jpg',
    'uy': 'https://www.fairytrail.app/img-assets/postcards/230%20-%20Uruguay.jpg',
    'uz': 'https://www.fairytrail.app/img-assets/postcards/231%20-%20Uzbekistan.jpg',
    'uzb': 'https://www.fairytrail.app/img-assets/postcards/231%20-%20Uzbekistan.jpg',
    'uzbekistan': 'https://www.fairytrail.app/img-assets/postcards/231%20-%20Uzbekistan.jpg',
    'va': 'https://www.fairytrail.app/img-assets/postcards/233%20-%20Vatican.jpg',
    'vanuatu': 'https://www.fairytrail.app/img-assets/postcards/232%20-%20Vanuatu.jpg',
    'vat': 'https://www.fairytrail.app/img-assets/postcards/233%20-%20Vatican.jpg',
    'vatican': 'https://www.fairytrail.app/img-assets/postcards/233%20-%20Vatican.jpg',
    'vatican city': 'https://www.fairytrail.app/img-assets/postcards/233%20-%20Vatican.jpg',
    'vc': 'https://www.fairytrail.app/img-assets/postcards/184%20-%20Saint%20Vincent%20and%20the%20Grenadines.jpg',
    'vct': 'https://www.fairytrail.app/img-assets/postcards/184%20-%20Saint%20Vincent%20and%20the%20Grenadines.jpg',
    've': 'https://www.fairytrail.app/img-assets/postcards/234%20-%20Venezuela.jpg',
    'ven': 'https://www.fairytrail.app/img-assets/postcards/234%20-%20Venezuela.jpg',
    'venezuela': 'https://www.fairytrail.app/img-assets/postcards/234%20-%20Venezuela.jpg',
    'vg': 'https://www.fairytrail.app/img-assets/postcards/31%20-%20British%20Virgin%20Islands.jpg',
    'vgb': 'https://www.fairytrail.app/img-assets/postcards/31%20-%20British%20Virgin%20Islands.jpg',
    'vi': 'https://www.fairytrail.app/img-assets/postcards/224%20-%20U.S.%20Virgin%20Islands.jpg',
    'viet nam': 'https://www.fairytrail.app/img-assets/postcards/235%20-%20Vietnam.jpg',
    'vietnam': 'https://www.fairytrail.app/img-assets/postcards/235%20-%20Vietnam.jpg',
    'vir': 'https://www.fairytrail.app/img-assets/postcards/224%20-%20U.S.%20Virgin%20Islands.jpg',
    'vn': 'https://www.fairytrail.app/img-assets/postcards/235%20-%20Vietnam.jpg',
    'vnm': 'https://www.fairytrail.app/img-assets/postcards/235%20-%20Vietnam.jpg',
    'vu': 'https://www.fairytrail.app/img-assets/postcards/232%20-%20Vanuatu.jpg',
    'vut': 'https://www.fairytrail.app/img-assets/postcards/232%20-%20Vanuatu.jpg',
    'wales': 'https://www.fairytrail.app/img-assets/postcards/228%20-%20United%20Kingdom.jpg',
    'wallis and futuna': 'https://www.fairytrail.app/img-assets/postcards/236%20-%20Wallis%20and%20Futuna.jpg',
    'western sahara': 'https://www.fairytrail.app/img-assets/postcards/237%20-%20Western%20Sahara.jpg',
    'wf': 'https://www.fairytrail.app/img-assets/postcards/236%20-%20Wallis%20and%20Futuna.jpg',
    'wlf': 'https://www.fairytrail.app/img-assets/postcards/236%20-%20Wallis%20and%20Futuna.jpg',
    'ws': 'https://www.fairytrail.app/img-assets/postcards/185%20-%20Samoa.jpg',
    'wsm': 'https://www.fairytrail.app/img-assets/postcards/185%20-%20Samoa.jpg',
    'xk': 'https://www.fairytrail.app/img-assets/postcards/111%20-%20Kosovo.jpg',
    'xkx': 'https://www.fairytrail.app/img-assets/postcards/111%20-%20Kosovo.jpg',
    'ye': 'https://www.fairytrail.app/img-assets/postcards/238%20-%20Yemen.jpg',
    'yem': 'https://www.fairytrail.app/img-assets/postcards/238%20-%20Yemen.jpg',
    'yemen': 'https://www.fairytrail.app/img-assets/postcards/238%20-%20Yemen.jpg',
    'yt': 'https://www.fairytrail.app/img-assets/postcards/134%20-%20Mayotte.jpg',
    'za': 'https://www.fairytrail.app/img-assets/postcards/199%20-%20South%20Africa.jpg',
    'zaf': 'https://www.fairytrail.app/img-assets/postcards/199%20-%20South%20Africa.jpg',
    'zambia': 'https://www.fairytrail.app/img-assets/postcards/239%20-%20Zambia.jpg',
    'zimbabwe': 'https://www.fairytrail.app/img-assets/postcards/240%20-%20Zimbabwe.jpg',
    'zm': 'https://www.fairytrail.app/img-assets/postcards/239%20-%20Zambia.jpg',
    'zmb': 'https://www.fairytrail.app/img-assets/postcards/239%20-%20Zambia.jpg',
    'zw': 'https://www.fairytrail.app/img-assets/postcards/240%20-%20Zimbabwe.jpg',
    'zwe': 'https://www.fairytrail.app/img-assets/postcards/240%20-%20Zimbabwe.jpg',
  };

  static const _displayNames = <String, String>{
    'abw': 'Aruba',
    'ad': 'Andorra',
    'ae': 'United Arab Emirates',
    'af': 'Afghanistan',
    'afg': 'Afghanistan',
    'afghanistan': 'Afghanistan',
    'ag': 'Antigua and Barbuda',
    'ago': 'Angola',
    'ai': 'Anguilla',
    'aia': 'Anguilla',
    'al': 'Albania',
    'alb': 'Albania',
    'albania': 'Albania',
    'algeria': 'Algeria',
    'am': 'Armenia',
    'america': 'USA',
    'american samoa': 'American Samoa',
    'an': 'Netherlands Antilles',
    'and': 'Andorra',
    'andorra': 'Andorra',
    'angola': 'Angola',
    'anguilla': 'Anguilla',
    'ant': 'Netherlands Antilles',
    'antarctica': 'Antarctica',
    'antigua and barbuda': 'Antigua and Barbuda',
    'ao': 'Angola',
    'aq': 'Antarctica',
    'ar': 'Argentina',
    'are': 'United Arab Emirates',
    'arg': 'Argentina',
    'argentina': 'Argentina',
    'arm': 'Armenia',
    'armenia': 'Armenia',
    'aruba': 'Aruba',
    'as': 'American Samoa',
    'asm': 'American Samoa',
    'at': 'Austria',
    'ata': 'Antarctica',
    'atg': 'Antigua and Barbuda',
    'au': 'Australia',
    'aus': 'Australia',
    'australia': 'Australia',
    'austria': 'Austria',
    'aut': 'Austria',
    'aw': 'Aruba',
    'az': 'Azerbaijan',
    'aze': 'Azerbaijan',
    'azerbaijan': 'Azerbaijan',
    'ba': 'Bosnia and Herzegovina',
    'bahamas': 'Bahamas',
    'bahrain': 'Bahrain',
    'bangladesh': 'Bangladesh',
    'barbados': 'Barbados',
    'bb': 'Barbados',
    'bd': 'Bangladesh',
    'bdi': 'Burundi',
    'be': 'Belgium',
    'bel': 'Belgium',
    'belarus': 'Belarus',
    'belgium': 'Belgium',
    'belize': 'Belize',
    'ben': 'Benin',
    'benin': 'Benin',
    'bermuda': 'Bermuda',
    'bf': 'Burkina Faso',
    'bfa': 'Burkina Faso',
    'bg': 'Bulgaria',
    'bgd': 'Bangladesh',
    'bgr': 'Bulgaria',
    'bh': 'Bahrain',
    'bhr': 'Bahrain',
    'bhs': 'Bahamas',
    'bhutan': 'Bhutan',
    'bi': 'Burundi',
    'bih': 'Bosnia and Herzegovina',
    'bj': 'Benin',
    'bl': 'Saint Barthelemy',
    'blm': 'Saint Barthelemy',
    'blr': 'Belarus',
    'blz': 'Belize',
    'bm': 'Bermuda',
    'bmu': 'Bermuda',
    'bn': 'Brunei',
    'bo': 'Bolivia',
    'bol': 'Bolivia',
    'bolivia': 'Bolivia',
    'bonaire': 'Bonaire',
    'bosnia and herzegovina': 'Bosnia and Herzegovina',
    'botswana': 'Botswana',
    'bq': 'Bonaire',
    'br': 'Brazil',
    'bra': 'Brazil',
    'brazil': 'Brazil',
    'brb': 'Barbados',
    'britain': 'United Kingdom',
    'british indian ocean territory': 'British Indian Ocean Territory',
    'british virgin islands': 'British Virgin Islands',
    'brn': 'Brunei',
    'brunei': 'Brunei',
    'bs': 'Bahamas',
    'bt': 'Bhutan',
    'btn': 'Bhutan',
    'bulgaria': 'Bulgaria',
    'burkina faso': 'Burkina Faso',
    'burma': 'Myanmar',
    'burundi': 'Burundi',
    'bw': 'Botswana',
    'bwa': 'Botswana',
    'by': 'Belarus',
    'bz': 'Belize',
    'ca': 'Canada',
    'caf': 'Central African Republic',
    'cambodia': 'Cambodia',
    'cameroon': 'Cameroon',
    'can': 'Canada',
    'canada': 'Canada',
    'cape verde': 'Cape Verde',
    'cayman islands': 'Cayman Islands',
    'cc': 'Cocos Islands',
    'cck': 'Cocos Islands',
    'cd': 'Democratic Republic of the Congo',
    'central african republic': 'Central African Republic',
    'cf': 'Central African Republic',
    'cg': 'Republic of the Congo',
    'ch': 'Switzerland',
    'chad': 'Chad',
    'che': 'Switzerland',
    'chile': 'Chile',
    'china': 'China',
    'chl': 'Chile',
    'chn': 'China',
    'christmas island': 'Christmas Island',
    'ci': 'Ivory Coast',
    'civ': 'Ivory Coast',
    'ck': 'Cook Islands',
    'cl': 'Chile',
    'cm': 'Cameroon',
    'cmr': 'Cameroon',
    'cn': 'China',
    'co': 'Colombia',
    'cocos islands': 'Cocos Islands',
    'cod': 'Democratic Republic of the Congo',
    'cog': 'Republic of the Congo',
    'cok': 'Cook Islands',
    'col': 'Colombia',
    'colombia': 'Colombia',
    'com': 'Comoros',
    'comoros': 'Comoros',
    'congo': 'Republic of the Congo',
    'congo-brazzaville': 'Republic of the Congo',
    'congo-kinshasa': 'Democratic Republic of the Congo',
    'cook islands': 'Cook Islands',
    'costa rica': 'Costa Rica',
    'cote d\'ivoire': 'Ivory Coast',
    'cote divoire': 'Ivory Coast',
    'cpv': 'Cape Verde',
    'cr': 'Costa Rica',
    'cri': 'Costa Rica',
    'croatia': 'Croatia',
    'cu': 'Cuba',
    'cub': 'Cuba',
    'cuba': 'Cuba',
    'curacao': 'Curacao',
    'cuw': 'Curacao',
    'cv': 'Cape Verde',
    'cw': 'Curacao',
    'cx': 'Christmas Island',
    'cxr': 'Christmas Island',
    'cy': 'Cyprus',
    'cym': 'Cayman Islands',
    'cyp': 'Cyprus',
    'cyprus': 'Cyprus',
    'cz': 'Czech Republic',
    'cze': 'Czech Republic',
    'czech republic': 'Czech Republic',
    'czechia': 'Czech Republic',
    'côte d\'ivoire': 'Ivory Coast',
    'de': 'Germany',
    'democratic republic of the congo': 'Democratic Republic of the Congo',
    'denmark': 'Denmark',
    'deu': 'Germany',
    'dj': 'Djibouti',
    'dji': 'Djibouti',
    'djibouti': 'Djibouti',
    'dk': 'Denmark',
    'dm': 'Dominica',
    'dma': 'Dominica',
    'dnk': 'Denmark',
    'do': 'Dominican Republic',
    'dom': 'Dominican Republic',
    'dominica': 'Dominica',
    'dominican republic': 'Dominican Republic',
    'dprk': 'North Korea',
    'dr congo': 'Democratic Republic of the Congo',
    'drc': 'Democratic Republic of the Congo',
    'dz': 'Algeria',
    'dza': 'Algeria',
    'east timor': 'East Timor',
    'ec': 'Ecuador',
    'ecu': 'Ecuador',
    'ecuador': 'Ecuador',
    'ee': 'Estonia',
    'eg': 'Egypt',
    'egy': 'Egypt',
    'egypt': 'Egypt',
    'eh': 'Western Sahara',
    'el salvador': 'El Salvador',
    'england': 'United Kingdom',
    'equatorial guinea': 'Equatorial Guinea',
    'er': 'Eritrea',
    'eri': 'Eritrea',
    'eritrea': 'Eritrea',
    'es': 'Spain',
    'esh': 'Western Sahara',
    'esp': 'Spain',
    'est': 'Estonia',
    'estonia': 'Estonia',
    'eswatini': 'Swaziland',
    'et': 'Ethiopia',
    'eth': 'Ethiopia',
    'ethiopia': 'Ethiopia',
    'falkland islands': 'Falkland Islands',
    'faroe islands': 'Faroe Islands',
    'fi': 'Finland',
    'fiji': 'Fiji',
    'fin': 'Finland',
    'finland': 'Finland',
    'fj': 'Fiji',
    'fji': 'Fiji',
    'fk': 'Falkland Islands',
    'flk': 'Falkland Islands',
    'fm': 'Micronesia',
    'fo': 'Faroe Islands',
    'fr': 'France',
    'fra': 'France',
    'france': 'France',
    'french polynesia': 'French Polynesia',
    'fro': 'Faroe Islands',
    'fsm': 'Micronesia',
    'fyrom': 'Macedonia',
    'ga': 'Gabon',
    'gab': 'Gabon',
    'gabon': 'Gabon',
    'gambia': 'Gambia',
    'gb': 'United Kingdom',
    'gbr': 'United Kingdom',
    'gd': 'Grenada',
    'ge': 'Georgia',
    'geo': 'Georgia',
    'georgia': 'Georgia',
    'germany': 'Germany',
    'gg': 'Guernsey',
    'ggy': 'Guernsey',
    'gh': 'Ghana',
    'gha': 'Ghana',
    'ghana': 'Ghana',
    'gi': 'Gibraltar',
    'gib': 'Gibraltar',
    'gibraltar': 'Gibraltar',
    'gin': 'Guinea',
    'gl': 'Greenland',
    'gm': 'Gambia',
    'gmb': 'Gambia',
    'gn': 'Guinea',
    'gnb': 'Guinea-Bissau',
    'gnq': 'Equatorial Guinea',
    'gp': 'Guadeloupe',
    'gq': 'Equatorial Guinea',
    'gr': 'Greece',
    'grc': 'Greece',
    'grd': 'Grenada',
    'great britain': 'United Kingdom',
    'greece': 'Greece',
    'greenland': 'Greenland',
    'grenada': 'Grenada',
    'grl': 'Greenland',
    'gt': 'Guatemala',
    'gtm': 'Guatemala',
    'gu': 'Guam',
    'guadeloupe': 'Guadeloupe',
    'guam': 'Guam',
    'guatemala': 'Guatemala',
    'guernsey': 'Guernsey',
    'guinea': 'Guinea',
    'guinea bissau': 'Guinea-Bissau',
    'guinea-bissau': 'Guinea-Bissau',
    'gum': 'Guam',
    'guy': 'Guyana',
    'guyana': 'Guyana',
    'gw': 'Guinea-Bissau',
    'gy': 'Guyana',
    'haiti': 'Haiti',
    'hk': 'Hong Kong',
    'hkg': 'Hong Kong',
    'hn': 'Honduras',
    'hnd': 'Honduras',
    'holland': 'Netherlands',
    'holy see': 'Vatican',
    'honduras': 'Honduras',
    'hong kong': 'Hong Kong',
    'hr': 'Croatia',
    'hrv': 'Croatia',
    'ht': 'Haiti',
    'hti': 'Haiti',
    'hu': 'Hungary',
    'hun': 'Hungary',
    'hungary': 'Hungary',
    'iceland': 'Iceland',
    'id': 'Indonesia',
    'idn': 'Indonesia',
    'ie': 'Ireland',
    'il': 'Israel',
    'im': 'Isle of Man',
    'imn': 'Isle of Man',
    'in': 'India',
    'ind': 'India',
    'india': 'India',
    'indonesia': 'Indonesia',
    'io': 'British Indian Ocean Territory',
    'iot': 'British Indian Ocean Territory',
    'iq': 'Iraq',
    'ir': 'Iran',
    'iran': 'Iran',
    'iraq': 'Iraq',
    'ireland': 'Ireland',
    'irl': 'Ireland',
    'irn': 'Iran',
    'irq': 'Iraq',
    'is': 'Iceland',
    'isl': 'Iceland',
    'isle of man': 'Isle of Man',
    'isr': 'Israel',
    'israel': 'Israel',
    'it': 'Italy',
    'ita': 'Italy',
    'italy': 'Italy',
    'ivory coast': 'Ivory Coast',
    'jam': 'Jamaica',
    'jamaica': 'Jamaica',
    'japan': 'Japan',
    'je': 'Jersey',
    'jersey': 'Jersey',
    'jey': 'Jersey',
    'jm': 'Jamaica',
    'jo': 'Jordan',
    'jor': 'Jordan',
    'jordan': 'Jordan',
    'jp': 'Japan',
    'jpn': 'Japan',
    'kaz': 'Kazakhstan',
    'kazakhstan': 'Kazakhstan',
    'ke': 'Kenya',
    'ken': 'Kenya',
    'kenya': 'Kenya',
    'kg': 'Kyrgyzstan',
    'kgz': 'Kyrgyzstan',
    'kh': 'Cambodia',
    'khm': 'Cambodia',
    'ki': 'Kiribati',
    'kir': 'Kiribati',
    'kiribati': 'Kiribati',
    'km': 'Comoros',
    'kn': 'Saint Kitts and Nevis',
    'kna': 'Saint Kitts and Nevis',
    'kor': 'South Korea',
    'kosovo': 'Kosovo',
    'kp': 'North Korea',
    'kr': 'South Korea',
    'kuwait': 'Kuwait',
    'kw': 'Kuwait',
    'kwt': 'Kuwait',
    'ky': 'Cayman Islands',
    'kyrgyzstan': 'Kyrgyzstan',
    'kz': 'Kazakhstan',
    'la': 'Laos',
    'lao': 'Laos',
    'laos': 'Laos',
    'latvia': 'Latvia',
    'lb': 'Lebanon',
    'lbn': 'Lebanon',
    'lbr': 'Liberia',
    'lby': 'Libya',
    'lc': 'Saint Lucia',
    'lca': 'Saint Lucia',
    'lebanon': 'Lebanon',
    'lesotho': 'Lesotho',
    'li': 'Liechtenstein',
    'liberia': 'Liberia',
    'libya': 'Libya',
    'lie': 'Liechtenstein',
    'liechtenstein': 'Liechtenstein',
    'lithuania': 'Lithuania',
    'lk': 'Sri Lanka',
    'lka': 'Sri Lanka',
    'lr': 'Liberia',
    'ls': 'Lesotho',
    'lso': 'Lesotho',
    'lt': 'Lithuania',
    'ltu': 'Lithuania',
    'lu': 'Luxembourg',
    'lux': 'Luxembourg',
    'luxembourg': 'Luxembourg',
    'lv': 'Latvia',
    'lva': 'Latvia',
    'ly': 'Libya',
    'ma': 'Morocco',
    'mac': 'Macau',
    'macao': 'Macau',
    'macau': 'Macau',
    'macedonia': 'Macedonia',
    'madagascar': 'Madagascar',
    'maf': 'Saint Martin',
    'malawi': 'Malawi',
    'malaysia': 'Malaysia',
    'maldives': 'Maldives',
    'mali': 'Mali',
    'malta': 'Malta',
    'mar': 'Morocco',
    'marshall islands': 'Marshall Islands',
    'mauritania': 'Mauritania',
    'mauritius': 'Mauritius',
    'mayotte': 'Mayotte',
    'mc': 'Monaco',
    'mco': 'Monaco',
    'md': 'Moldova',
    'mda': 'Moldova',
    'mdg': 'Madagascar',
    'mdv': 'Maldives',
    'me': 'Montenegro',
    'mex': 'Mexico',
    'mexico': 'Mexico',
    'mf': 'Saint Martin',
    'mg': 'Madagascar',
    'mh': 'Marshall Islands',
    'mhl': 'Marshall Islands',
    'micronesia': 'Micronesia',
    'mk': 'Macedonia',
    'mkd': 'Macedonia',
    'ml': 'Mali',
    'mli': 'Mali',
    'mlt': 'Malta',
    'mm': 'Myanmar',
    'mmr': 'Myanmar',
    'mn': 'Mongolia',
    'mne': 'Montenegro',
    'mng': 'Mongolia',
    'mnp': 'Northern Mariana Islands',
    'mo': 'Macau',
    'moldova': 'Moldova',
    'monaco': 'Monaco',
    'mongolia': 'Mongolia',
    'montenegro': 'Montenegro',
    'montserrat': 'Montserrat',
    'morocco': 'Morocco',
    'moz': 'Mozambique',
    'mozambique': 'Mozambique',
    'mp': 'Northern Mariana Islands',
    'mr': 'Mauritania',
    'mrt': 'Mauritania',
    'ms': 'Montserrat',
    'msr': 'Montserrat',
    'mt': 'Malta',
    'mu': 'Mauritius',
    'mus': 'Mauritius',
    'mv': 'Maldives',
    'mw': 'Malawi',
    'mwi': 'Malawi',
    'mx': 'Mexico',
    'my': 'Malaysia',
    'myanmar': 'Myanmar',
    'mys': 'Malaysia',
    'myt': 'Mayotte',
    'mz': 'Mozambique',
    'na': 'Namibia',
    'nam': 'Namibia',
    'namibia': 'Namibia',
    'nauru': 'Nauru',
    'nc': 'New Caledonia',
    'ncl': 'New Caledonia',
    'ne': 'Niger',
    'nepal': 'Nepal',
    'ner': 'Niger',
    'netherlands': 'Netherlands',
    'netherlands antilles': 'Netherlands Antilles',
    'new caledonia': 'New Caledonia',
    'new zealand': 'New Zealand',
    'ng': 'Nigeria',
    'nga': 'Nigeria',
    'ni': 'Nicaragua',
    'nic': 'Nicaragua',
    'nicaragua': 'Nicaragua',
    'niger': 'Niger',
    'nigeria': 'Nigeria',
    'niu': 'Niue',
    'niue': 'Niue',
    'nl': 'Netherlands',
    'nld': 'Netherlands',
    'no': 'Norway',
    'nor': 'Norway',
    'north korea': 'North Korea',
    'north macedonia': 'Macedonia',
    'northern mariana islands': 'Northern Mariana Islands',
    'norway': 'Norway',
    'np': 'Nepal',
    'npl': 'Nepal',
    'nr': 'Nauru',
    'nru': 'Nauru',
    'nu': 'Niue',
    'nz': 'New Zealand',
    'nzl': 'New Zealand',
    'om': 'Oman',
    'oman': 'Oman',
    'omn': 'Oman',
    'pa': 'Panama',
    'pak': 'Pakistan',
    'pakistan': 'Pakistan',
    'palau': 'Palau',
    'palestine': 'Palestine',
    'pan': 'Panama',
    'panama': 'Panama',
    'papua new guinea': 'Papua New Guinea',
    'paraguay': 'Paraguay',
    'pcn': 'Pitcairn',
    'pe': 'Peru',
    'per': 'Peru',
    'peru': 'Peru',
    'pf': 'French Polynesia',
    'pg': 'Papua New Guinea',
    'ph': 'Philippines',
    'philippines': 'Philippines',
    'phl': 'Philippines',
    'pitcairn': 'Pitcairn',
    'pk': 'Pakistan',
    'pl': 'Poland',
    'plw': 'Palau',
    'pm': 'Saint Pierre and Miquelon',
    'pn': 'Pitcairn',
    'png': 'Papua New Guinea',
    'pol': 'Poland',
    'poland': 'Poland',
    'portugal': 'Portugal',
    'pr': 'Puerto Rico',
    'pri': 'Puerto Rico',
    'prk': 'North Korea',
    'prt': 'Portugal',
    'pry': 'Paraguay',
    'ps': 'Palestine',
    'pse': 'Palestine',
    'pt': 'Portugal',
    'puerto rico': 'Puerto Rico',
    'pw': 'Palau',
    'py': 'Paraguay',
    'pyf': 'French Polynesia',
    'qa': 'Qatar',
    'qat': 'Qatar',
    'qatar': 'Qatar',
    're': 'Reunion',
    'republic of korea': 'South Korea',
    'republic of the congo': 'Republic of the Congo',
    'reu': 'Reunion',
    'reunion': 'Reunion',
    'ro': 'Romania',
    'romania': 'Romania',
    'rou': 'Romania',
    'rs': 'Serbia',
    'ru': 'Russia',
    'rus': 'Russia',
    'russia': 'Russia',
    'russian federation': 'Russia',
    'rw': 'Rwanda',
    'rwa': 'Rwanda',
    'rwanda': 'Rwanda',
    'sa': 'Saudi Arabia',
    'saint barthelemy': 'Saint Barthelemy',
    'saint helena': 'Saint Helena',
    'saint kitts and nevis': 'Saint Kitts and Nevis',
    'saint lucia': 'Saint Lucia',
    'saint martin': 'Saint Martin',
    'saint pierre and miquelon': 'Saint Pierre and Miquelon',
    'saint vincent and the grenadines': 'Saint Vincent and the Grenadines',
    'samoa': 'Samoa',
    'san marino': 'San Marino',
    'sao tome and principe': 'Sao Tome and Principe',
    'sau': 'Saudi Arabia',
    'saudi arabia': 'Saudi Arabia',
    'sb': 'Solomon Islands',
    'sc': 'Seychelles',
    'scotland': 'United Kingdom',
    'sd': 'Sudan',
    'sdn': 'Sudan',
    'se': 'Sweden',
    'sen': 'Senegal',
    'senegal': 'Senegal',
    'serbia': 'Serbia',
    'seychelles': 'Seychelles',
    'sg': 'Singapore',
    'sgp': 'Singapore',
    'sh': 'Saint Helena',
    'shn': 'Saint Helena',
    'si': 'Slovenia',
    'sierra leone': 'Sierra Leone',
    'singapore': 'Singapore',
    'sint maarten': 'Sint Maarten',
    'sj': 'Svalbard and Jan Mayen',
    'sjm': 'Svalbard and Jan Mayen',
    'sk': 'Slovakia',
    'sl': 'Sierra Leone',
    'slb': 'Solomon Islands',
    'sle': 'Sierra Leone',
    'slovakia': 'Slovakia',
    'slovenia': 'Slovenia',
    'slv': 'El Salvador',
    'sm': 'San Marino',
    'smr': 'San Marino',
    'sn': 'Senegal',
    'so': 'Somalia',
    'solomon islands': 'Solomon Islands',
    'som': 'Somalia',
    'somalia': 'Somalia',
    'south africa': 'South Africa',
    'south korea': 'South Korea',
    'south sudan': 'South Sudan',
    'spain': 'Spain',
    'spm': 'Saint Pierre and Miquelon',
    'sr': 'Suriname',
    'srb': 'Serbia',
    'sri lanka': 'Sri Lanka',
    'ss': 'South Sudan',
    'ssd': 'South Sudan',
    'st': 'Sao Tome and Principe',
    'stp': 'Sao Tome and Principe',
    'sudan': 'Sudan',
    'sur': 'Suriname',
    'suriname': 'Suriname',
    'sv': 'El Salvador',
    'svalbard and jan mayen': 'Svalbard and Jan Mayen',
    'svk': 'Slovakia',
    'svn': 'Slovenia',
    'swaziland': 'Swaziland',
    'swe': 'Sweden',
    'sweden': 'Sweden',
    'switzerland': 'Switzerland',
    'swz': 'Swaziland',
    'sx': 'Sint Maarten',
    'sxm': 'Sint Maarten',
    'sy': 'Syria',
    'syc': 'Seychelles',
    'syr': 'Syria',
    'syria': 'Syria',
    'sz': 'Swaziland',
    'taiwan': 'Taiwan',
    'tajikistan': 'Tajikistan',
    'tanzania': 'Tanzania',
    'tc': 'Turks and Caicos Islands',
    'tca': 'Turks and Caicos Islands',
    'tcd': 'Chad',
    'td': 'Chad',
    'tg': 'Togo',
    'tgo': 'Togo',
    'th': 'Thailand',
    'tha': 'Thailand',
    'thailand': 'Thailand',
    'tj': 'Tajikistan',
    'tjk': 'Tajikistan',
    'tk': 'Tokelau',
    'tkl': 'Tokelau',
    'tkm': 'Turkmenistan',
    'tl': 'East Timor',
    'tls': 'East Timor',
    'tm': 'Turkmenistan',
    'tn': 'Tunisia',
    'to': 'Tonga',
    'togo': 'Togo',
    'tokelau': 'Tokelau',
    'ton': 'Tonga',
    'tonga': 'Tonga',
    'tr': 'Turkey',
    'trinidad and tobago': 'Trinidad and Tobago',
    'tt': 'Trinidad and Tobago',
    'tto': 'Trinidad and Tobago',
    'tun': 'Tunisia',
    'tunisia': 'Tunisia',
    'tur': 'Turkey',
    'turkey': 'Turkey',
    'turkmenistan': 'Turkmenistan',
    'turks and caicos islands': 'Turks and Caicos Islands',
    'tuv': 'Tuvalu',
    'tuvalu': 'Tuvalu',
    'tv': 'Tuvalu',
    'tw': 'Taiwan',
    'twn': 'Taiwan',
    'tz': 'Tanzania',
    'tza': 'Tanzania',
    'u s virgin islands': 'U.S. Virgin Islands',
    'u.s. virgin islands': 'U.S. Virgin Islands',
    'ua': 'Ukraine',
    'uae': 'United Arab Emirates',
    'ug': 'Uganda',
    'uga': 'Uganda',
    'uganda': 'Uganda',
    'uk': 'United Kingdom',
    'ukr': 'Ukraine',
    'ukraine': 'Ukraine',
    'united arab emirates': 'United Arab Emirates',
    'united kingdom': 'United Kingdom',
    'united states': 'USA',
    'united states of america': 'USA',
    'uruguay': 'Uruguay',
    'ury': 'Uruguay',
    'us': 'USA',
    'usa': 'USA',
    'uy': 'Uruguay',
    'uz': 'Uzbekistan',
    'uzb': 'Uzbekistan',
    'uzbekistan': 'Uzbekistan',
    'va': 'Vatican',
    'vanuatu': 'Vanuatu',
    'vat': 'Vatican',
    'vatican': 'Vatican',
    'vatican city': 'Vatican',
    'vc': 'Saint Vincent and the Grenadines',
    'vct': 'Saint Vincent and the Grenadines',
    've': 'Venezuela',
    'ven': 'Venezuela',
    'venezuela': 'Venezuela',
    'vg': 'British Virgin Islands',
    'vgb': 'British Virgin Islands',
    'vi': 'U.S. Virgin Islands',
    'viet nam': 'Vietnam',
    'vietnam': 'Vietnam',
    'vir': 'U.S. Virgin Islands',
    'vn': 'Vietnam',
    'vnm': 'Vietnam',
    'vu': 'Vanuatu',
    'vut': 'Vanuatu',
    'wales': 'United Kingdom',
    'wallis and futuna': 'Wallis and Futuna',
    'western sahara': 'Western Sahara',
    'wf': 'Wallis and Futuna',
    'wlf': 'Wallis and Futuna',
    'ws': 'Samoa',
    'wsm': 'Samoa',
    'xk': 'Kosovo',
    'xkx': 'Kosovo',
    'ye': 'Yemen',
    'yem': 'Yemen',
    'yemen': 'Yemen',
    'yt': 'Mayotte',
    'za': 'South Africa',
    'zaf': 'South Africa',
    'zambia': 'Zambia',
    'zimbabwe': 'Zimbabwe',
    'zm': 'Zambia',
    'zmb': 'Zambia',
    'zw': 'Zimbabwe',
    'zwe': 'Zimbabwe',
  };

  /// Featured countries shown first in trail-book filters when present.
  static const knownCountries = <String>['India', 'Japan', 'USA', 'Vietnam'];

  /// CDN URL for a free-form [senderLocation] like `"Tokyo, Japan"`, or null
  /// when unknown (caller should use [defaultAsset]).
  static String? urlForLocation(String? senderLocation) {
    final key = countryKey(senderLocation);
    if (key == null) return null;
    return _urls[key];
  }

  /// Display label for the card footer (e.g. `"Japan"`).
  static String displayCountry(String? senderLocation) {
    final raw = (senderLocation ?? '').trim();
    if (raw.isEmpty) return '';
    final country = _countryFromLocation(raw);
    if (country.isEmpty) return raw;
    final key = country.toLowerCase();
    final mapped = _displayNames[key];
    if (mapped != null) return mapped;
    // Title-case single/multi-word country names.
    return country
        .split(RegExp(r'\s+'))
        .where((w) => w.isNotEmpty)
        .map((w) => '${w[0].toUpperCase()}${w.substring(1).toLowerCase()}')
        .join(' ');
  }

  /// Normalized lowercase key used for URL lookup, or null if unknown.
  static String? countryKey(String? senderLocation) {
    final country = _countryFromLocation(senderLocation ?? '');
    if (country.isEmpty) return null;
    final key = country.toLowerCase();
    if (_urls.containsKey(key)) return key;
    return null;
  }

  static bool matchesFilter(String senderLocation, String filter) {
    if (filter == 'All') return true;
    final display = displayCountry(senderLocation).toLowerCase();
    return display == filter.toLowerCase();
  }

  static String _countryFromLocation(String location) {
    final trimmed = location.trim();
    if (trimmed.isEmpty) return '';
    final parts = trimmed.split(',');
    return parts.last.trim();
  }
}
